### ISSUE TITLE
Using Intel MPI, seeing report of NaN in reprosum from phys_gmean with ne4 F-case

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#2302]
I'm using Intel MPI instead of the default/trusted Cray MPICH to better use some Intel tools, but also as an additional test.  This is with ne4 F case. 

If we see this message, does that mean there is an issue in the code that is calling the global sum?

Is there an easy way to "turn this off" and let it run further to verify this is an isolated problem or not?

```
47: SHR_REPROSUM_CALC: Input contains  0.11000E+02 NaNs and  0.00000E+00 INFs on process      47
47:  ERROR: shr_reprosum_calc ERROR: NaNs or INFs in input
47: Image              PC                Routine            Line        Source
47: e3sm.exe           0000000002A333F6  Unknown               Unknown  Unknown
47: e3sm.exe           000000000242CBEF  shr_abort_mod_mp_         114  shr_abort_mod.F90
47: e3sm.exe           000000000257B6FE  shr_reprosum_mod_         428  shr_reprosum_mod.F90
47: e3sm.exe           00000000005C0327  phys_gmean_mp_gme         414  phys_gmean.F90
47: e3sm.exe           00000000005BC3FC  phys_gmean_mp_gme          83  phys_gmean.F90
47: e3sm.exe           000000000105CA80  check_energy_mp_c         609  check_energy.F90
47: e3sm.exe           0000000000617B83  physpkg_mp_phys_r         982  physpkg.F90
47: e3sm.exe           000000000050641B  cam_comp_mp_cam_r         250  cam_comp.F90
47: e3sm.exe           00000000004F3B15  atm_comp_mct_mp_a         522  atm_comp_mct.F90
47: e3sm.exe           0000000000439134  component_mod_mp_         728  component_mod.F90
47: e3sm.exe           000000000041E427  cime_comp_mod_mp_        3375  cime_comp_mod.F90
47: e3sm.exe           0000000000438E40  MAIN__                    103  cime_driver.F90
47: e3sm.exe           000000000041A49E  Unknown               Unknown  Unknown
47: libc-2.22.so       00002AAAC632C6D5  __libc_start_main     Unknown  Unknown
47: e3sm.exe           000000000041A3A9  Unknown               Unknown  Unknown
```

**Comment by worleyph** [comment]
This issue has been further pursued via email exchanges between @ndkeen , @worleyph, and @jayeshkrishna and extensive experimentation. The latest summary is that ...

We have tracked this down to (at least) incorrect results when rearranging data within PIO when reading initial data. (This was using a two process ne4 F case on Cori-KNL.) Note that the Intel MPI library works fine for this case on Bebop. I have not tried the other NERSC systems - only Cori-KNL.

My hypothesis is that the issue has something to do with the MPI derived data type, but it works the first time (reading and rearranging U velocity) and then starts failing in subsequent reads/rearranges (V velocity is the second one), and U and V use the identical derived datatypes.  Based on examing bounds and extents, the datatypes are not corrupted. All of the diagnostic output when comparing Cray mpich and Intel MPI are the same - it is just that the values sent from process 0 to process 1 that are different (in this second call). The data being sent is the same each time (so deterministic) and the values are "reasonable". The values just aren't found in the source buffer on process 0, so I don't know where they are coming from. (The destination array is zeroed out before the rearranger call, so data are being copied into the destination array.)

There are three ways of communicating data in the rearranger command: native isend/irecv, MPI_AlltoallW, and swapm. The data transferred to process 1 for V velocity are identical for native isend/irecv and MPI_AlltoallW (and I assume for swapm, though I have not tried this), so it is not an issue with the communication protocol.

The only other information is that there is a ping-pong test in PIO1. Enabling this (call comp2io immediately after calling io2comp), the "pong" fails even in the first call (for U velocity). Looking at the details, only zeroes are communicated back to process 0 from process 1 (or perhaps nothing is communicated and I am just seeing the zeroes from the initialization - I need to check). However, two back-to-back calls of io2comp for the U velocity work correctly, so the first failure of the io2comp is for the V velocity, and not just from executing io2comp more than once.

Note that process 0 to process 0 "communication" is correct in all of the experiments. 

I've run out of ideas on how to diagnose this. Since it does not affect production runs using the default MPI libraries on any of our systems, this is not critical. It does appear to be an Intel MPI library bug on Cori-KNL rather than a model bug, but we do not have a reproducer to provide NERSC other that the whole code, so submitting a bug report probably would not do much. Developing a reproducer would probably require extracting both the MPI derived datatype logic and the io2comp logic, which is not something I would find easy to do.

**Comment by amametjanov** [comment]
Running with netcdf (instead of pnetcdf) might help.

**Comment by worleyph** [comment]
@amametjanov , this works fine with Cray mpich. Do you know of any interactions between the Intel MPI library and netcdf on other systems? Worth trying though - nothing else has worked.

**Comment by amametjanov** [comment]
Nothing else I tried on Bebop worked.

**Comment by ndkeen** [comment]
Only noting that Pat and I have been communicating and I agree with Pat. Leaving as open issue for now.

**Comment by ndkeen** [comment]
After updating to a newer impi version(https://github.com/E3SM-Project/E3SM/pull/2442), I'm no longer seeing this error, so closing issue.
