### ISSUE TITLE
Aquaplanet compset is not an aquaplanet?

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2383]
It appears as though the FC5AV1C-04P2-AQUAP compset is not actually an aquaplanet. I can configure, build, and run a case with this compset just fine, but the output reflects topography features in the surface pressure:

![aqua_ps](https://user-images.githubusercontent.com/15826727/41053579-3869f5e6-6979-11e8-89e8-ace2f3039395.png)

So, either something isn't being set properly, or I am misunderstanding what "AQUAP" is supposed to mean in this compset definition.

**Comment by oksanaguba** [comment]
There is a surf. geopotential field in cam.h0 files:
	float PHIS(time, ncol) ;
		PHIS:units = "m2/s2" ;
		PHIS:long_name = "Surface geopotential" ;
Would it be const in your run? If your run is on skybridge, I can try to plot it.

**Comment by brhillman** [comment]
Nope, not constant:

![aqua_phis](https://user-images.githubusercontent.com/15826727/41054975-33746040-697d-11e8-9141-6f5c574bc290.png)

Yes, run is on skybridge, case directory here:

/ascldap/users/bhillma/data/acme_scratch/cases/master.FC5AV1C-04P2-AQUAP.ne30_ne30

and run directory here:

/gscratch/bhillma/acme_scratch/sandiatoss3/master.FC5AV1C-04P2-AQUAP.ne30_ne30/run

**Comment by rljacob** [comment]
This is a real bug.  I suspect something in the EAM configure isn't being passed correctly.

**Comment by whannah1** [comment]
FWIW, I think this was inherited from CAM, since I saw this many years ago.

**Comment by singhbalwinder** [comment]
Thanks for testing this compset. I am tagging @huiwanpnnl and @zhangshixuan1987 so that they are aware of this issue. I think we just mimicked what AQAP configuration for FC5 was and did not test it thoroughly except some smoke tests. Thanks for brining this up, this definitely needs to be fixed.

**Comment by singhbalwinder** [comment]
@zhangshixuan1987 did some quick tests and found out (as reported by @whannah1 ) that this issue exists in CAM as well. We mimicked CAM's compset, so it exists in our compset as well. @zhangshixuan1987 is working on a hypothesis that it might be due to the IC file that we are using.

**Comment by dazlich** [comment]
Is this an instantaneous flattening? I once did an aquaplanet experiment with the CSU model where I took two days to gradually flatten the topography (a proportional amount every timestep) and that seemed to work ok for me.

On Jun 21, 2018, at 3:27 PM, Walter Hannah <notifications@github.com<mailto:notifications@github.com>> wrote:


I've recently been working on some aqua-planet stuff and thought I'd chime in on this issue.
When I initially tried to flatten the topography for some aqua runs with a custom SST distribution the runs died immediately with negative thickness errors. It makes sense that the default initialization file would be problematic since the surface pressure over the Hymalayas is stronger than any hurricane we've observed.

I tried to follow the spin up procedures for running with a new grid, but it seemed like no matter how high I set the hyperviscosity or other dycor parameters, I just could not get it to work. Eventually I got something to run for a bit, but the timestep was so small and the other settings were so large that it would have taken a very long time to get through a single day.

I developed some NCL code to do horizontal smoothing on the cubed sphere grid without any regridding, so I got a smoothed input file that I could feed into the aqua run. The surface pressure looked like this:
[aqua init smoothing]<https://user-images.githubusercontent.com/9679059/41746104-0b55d606-755e-11e8-9a04-76de4ca7c642.png>

The surface pressure is still unrealistically low, but I gave it a try anyway. I still had to crank up the hyperviscosity and remapping parameters, but I got it to run a bit with the super-parameterized model. I haven't tried with the standard parameterized E3SM. The run gets through half a day before crashing. A look at the output shows several sharp wave fronts that originate in the low pressure areas and propagate very fast.
[screen shot 2018-06-21 at 2 23 32 pm]<https://user-images.githubusercontent.com/9679059/41746371-f26762f8-755e-11e8-9a82-0a5185706c7e.png>

I'm working on a new version of the cami file that applies much stronger smoothing. I should be able to test it tonight or tomorrow. If it works then we can put something like this in the input data repo.

**Comment by whannah1** [comment]
@dazlich, my experiments are instantaneous, so it's not surprising that it crashed initially. I like your solution of a gradual flattening. Either way, it seems that we need a new initial condition file for aqua planet runs.

**Comment by singhbalwinder** [comment]
We (@zhangshixuan1987 , @huiwanpnnl and I) talked about it and Hui mentioned that she faced similar issues until she followed the instructions on http://www.cesm.ucar.edu/models/simpler-models/fixed_sst_aqua.html. Currently the aqua-planet compset is not a true aqua planet compset as it just exclude the land model (by making it a stub model). 

@huiwanpnnl mentioned that true aqua planet configuration  works best with CAM4 as CAM5 may have height dependent emissions, which add effects from topography into the simulation. 

@huiwanpnnl and @zhangshixuan1987 : Please feel free to add more details about what you have learnt running the aqua planet simulations.

**Comment by rljacob** [comment]
If a special IC file has to be created, its very likely that was never done for SE.
Its also possible the right options aren't being passed to the CAM configure.

**Comment by singhbalwinder** [comment]
> If a special IC file has to be created, its very likely that was never done for SE.

- yes, we currently using the default IC file. @zhangshixuan1987 pointed me to this file which CESM model uses for aquaplanet :`'/glade/u/home/benedict/ys/datain/ape.IC.2deg.0003-01-01-00000.nc'`. We need to regrid/remap this file for ne grids with 72 levels.





> Its also possible the right options aren't being passed to the CAM configure.

--They are listed on the webpage I pointed out. It should not be hard to automate them by using usecase and configure options in the code.

**Comment by zhangshixuan1987** [comment]
As indicated by Balwinder, Our goal is to turn off the land model, we do not try to run the real aquaplanet simulation. 

For E3SM, as mentioned by @huiwanpnnl, the tips for the aquaplanet simulation include:
1. you need to explicitly set "aqua_planet" (in cam_control_mod module) to "true". This logical variable is false by default if you did not explicitly set it up.
2. orbital model setting, including eccentricity, obliquity of orbit etc. 
3. properly configure the physics package for aquaplanet. 
4. spin up suitable initial conditions, if you use the initial conditions from the full model, you need to follow the 1-3, and spin up the model for few months.  
The website as pointed out by @singhbalwinder is a good reference to set up 1-3.

**Comment by rljacob** [comment]
What is the difference between "turning off the land model" and "real aquaplanet simulation"?

**Comment by rljacob** [comment]
The CESM webpage above is for CESM1.2 and not a good guide for what we should do.  Look at how CAM6 does an aquaplanet.  That will be closer to what we should do.  The DOCN now has the most advanced aquaplanet capability and we should not use the internal aquaplanet of CAM/EAM.

**Comment by zhangshixuan1987** [comment]
The difference is that the aquaplanet composite configures the slab ocean model rather than CLM model for the land surface.  This is the major reason we use the aquaplanet compset ( to turn off the CLM land model), we did not change the configurations follow steps 1-4 as I mentioned above. But the "real aquaplanet simulation" should follow the steps 1-4 to change the configurations.

**Comment by rljacob** [comment]
All you need is an initial condition file with a flat topography and SLP.  The compset does mostly the right thing.  The CAM configure should sub in the initial condition file so you don't need special aquaplanet versions of every CAM_NML_USE_CASE.

**Comment by whannah1** [comment]
@zhangshixuan1987, so I've been using "DOCN%DOM" in my aqua-planet runs so that I could specify my own custom "SSTICE_DATA_FILENAME" in env_run.xml. Is it still possible to do this if I use "DOCN%AQP1"?

Also, are the emissions controlled by an input file? Do we need to create a null emissions file?

**Comment by singhbalwinder** [comment]
> Also, are the emissions controlled by an input file? Do we need to create a null emissions file?

I think emissions are controlled by individual files for each aerosol specie. Depending on the chemistry options, aerosols and their respective files are selected from namelist_defaults.xml file. Input file just have initial values for each aerosol specie.

**Comment by whannah1** [comment]
ah, so maybe the easier way to avoid aerosol/chem complications is to use "-chem none" and find a way to disable aerosol radiative calculations. We would also have to make sure linoz gets disabled and maybe something else I'm forgetting about.

**Comment by huiwanpnnl** [comment]
I think it will be useful to clarify what kind of aqua-planet simulations we would like the model to support.
In a strict sense, an aqua-planet simulation should follow one of the specifications from the aqua-planet model inter-comparison project, [see here](http://www.met.reading.ac.uk/~mike/APE/proposal.html). According to their protocol, the simulations not only need to assume a water-covered planet with flat surface, but also would use one of the specified SST fields, and set the solar insolation at March equinoctial conditions. (The protocol was created at a time when most atmosphere models only considered the aerosols' radiative effects but not the interactions with clouds. The aerosol concentrations were probably specified using input data files or hardwired numbers in the code.)
In a much looser sense, we could also say an aqua-planet simulation is simply a simulation on a water-covered planet with flat surface. We could allow the user to specify the SST and the Earth orbit parameters, so that they could use such configurations for a wider range of scientific and model development purposes.

**Comment by lrleung** [comment]
I also think that we should allow the users to specific the SST and orbital parameters for aquaplanet simulations. As for aerosols, I think there is already a zonally symmetric aerosol input data developed for aquaplanet simulations using CAM5. We’ve used it for the TRACMIP project before.

**Comment by whannah1** [comment]
@huiwanpnnl, I think using the aqua-planet MIP as a guide is a good idea. However, the part about specifying constant March radiation might be problematic. I tried to do this with CESM 1.2.2 awhile back and couldn't figure out how to do it. I normally just change the orbital parameters to get a perpetual equinox.

**Comment by huiwanpnnl** [comment]
@whannah1, changing the orbital parameters seems the right way to me.

**Comment by whannah1** [comment]
@huiwanpnnl, but then we are limited to only using perpetual equinox. We can't have other perpetual seasons, which would allow some interesting experiments that I've always wanted to explore. For now, I think an default equinox setting would be fine, but maybe after RRTMG-P gets added in we should look into adding a mechanism for doing these types of experiments.

**Comment by huiwanpnnl** [comment]
@whannah1, these might be relevant:

**components/cam/src/utils/cam_dom/sst_data.F90, subroutine sstini:**

  if(aqua_planet) then
     call prescribed_sst()
     return
  end if

**components/cam/src/utils/cam_aqua/ocn_comp.F90, subroutine prescribed_sst**.

**Comment by huiwanpnnl** [comment]
@whannah1, I have to admit I never looked into orbit-related modules in the model, so what I say here might be nonsense:

The function **shr_orb_cosz** in **components/homme/utils/cime/src/share/util/shr_orb_mod.F90** has an argument **jday** (Julian calendar day). If we allow this function to use a user-specified (fixed) Julian day instead of the actual calendar day, that might give you other perpetual seasons than equinox?

**Comment by whannah1** [comment]
Thanks @huiwanpnnl! 
It looks like these options match the APE SST patterns, but it also appears that "sst_option" is hardcoded to 1, so I'm guessing the compset modifier won't affect the pattern.

As for shr_orb_cosz(), I think I looked into this, but I never tested fixing the jday value. I'll try to do a test of that soon.

**Comment by mt5555** [comment]
this might be useful or might be out of date:  it's a document on running CAM5 APE from a couple of years ago:

https://docs.google.com/document/d/10SX7xD0OZ3cb7rEtG33BTEofVej45akxRmebQ_yfHyg/edit?usp=sharing

much of which comes from Colin Zarzycki.  In particular: you want a  symmetric ozone file, symmetric prescribed aerosols file with ( -chem none -nadv 5 ).  These are lat/lon files and will be interpolated to the SE grid inline.

Colin also has a L30 APE IC file that can be interpolated to E3SM's L72 configuraiton with CAM's intperic_new utility.

**Comment by whannah1** [comment]
@rljacob, fixing the orbital parameters won't fix the season, except for the case of a perpetual equinox.  Fixing the season requires hijacking the solar radiation so that the planet effectively spins in place and does not orbit.

**Comment by whannah1** [comment]
FYI, I was able to get a simulation running for over a day with 5 min time step and increased dycor parameters:
- qsplit            = 20
- rsplit            = 20
- se_nsplit         = 20
- hypervis_subcycle = 20

This still had some "shock fronts" but it ran ok. I took the resulting cam.i file and shot off another run with a standard setup and it seems to be running just fine! It's already through the first month. 

I should mention that this is a super-parameterized run with a warm-pool SST configuration, but I also did a standard E3SM run with the above settings and my smoothed input file and it ran ok. So maybe we should generate a new cam.i file using the AQUAP analytic SST pattern and set up all AQUAP compseta to use that cam.i file by default. I have a topo file with the heights zeroed out as well that I can provide. I don't think we'll need separate cam.i files for the different APE SST options.

In case anyone is interested in how the simulation looks, here's some ncview plots from the first monthly mean file.

near-surface air temperature (TS):
![image](https://user-images.githubusercontent.com/9679059/41927640-a124fdca-7927-11e8-83bd-63c31b944c6d.png)

surface pressure (PS):
![image](https://user-images.githubusercontent.com/9679059/41927543-64b47f6e-7927-11e8-82c3-d2fb8bb9fe1c.png)

Precipitation:
![image](https://user-images.githubusercontent.com/9679059/41927671-b53f0d28-7927-11e8-906e-edad46059358.png)

**Comment by mt5555** [comment]
Reviving this thread since I'd also like to run some aqua planet simulations.

A couple of notes:  If you add "-aquaplanet" to the env_build.xml::CAM_CONFIG_OPTS, then you will get aqua_planet=.true. set in drv_in.    With this flag true, I believe CAM will set the topography to zero and ignore the nctopo namelist variable.  Setting this flag to .true. may turn on other things needed for a true aqua planet simulation (and would avoid the need to create a PHIS=0 nctopo file).

Looking at the CESM aquaplanet compsets:  they use "use cases", such as aquaplanet_cam5.xml,
which sets the perpetual spring orbital parameters.   

I added this to the env_run.xml USE_CASE variable.  Running preview_namelist, I see that it sets all the CAM parameters, but it ignores the drv_in paramemerts (which include the orbital settings).

This must be a bug in E3SM.
