### ISSUE TITLE
Unsupported OCN, ICE decompositions not caught during case.setup or case.build

### ISSUE THREAD

**Issue by worleyph** [E3SM-Project/E3SM#2400]
After editing env_mach_specific.xml to set NTASKS for OCN or ICE  to something for which there is not a corresponding partition file, a warning/failure is not generated by either ./case.setup or ./case.build. The problem is not identified until ./case.submit . This is a change of behavior (if we go back far enough?)

Perhaps this is a planned change (and I was just not paying attention), but it is inconvenient to not realize that there is a problem until runtime, as fixing it requires changing the PE layout and then recompiling. I want to verify that this is the intended behavior, and ask if there is a convenient to check whether an MPAS decomposition exists or not (other than manually looking in inputdata).

**Comment by rljacob** [comment]
**Is** that a change in behavior?

**Comment by singhbalwinder** [comment]
If I remember correctly, it fails when it tries to download a non-existent partition file. It use to check for files during case.setup but now it looks for files during case.submit. It has been a while since I ran into this error so the above may not be entirely accurate but I did notice the change in this behavior. As far as I know, this change is not recent.

**Comment by worleyph** [comment]
@singhbalwinder , thanks. Was afraid that I was misremembering. I generally avoid the error by looking inside inputdata to see what partition files are available. I was feeling lazy, and decided to let case.setup tell me whether my choice was correct or not, and was surprised that it did not appear to even check.

Perhaps this is better listed as a feature request - some tool to query whether a given partition file exists. I know that at some point we were going to generate partition files on the fly, but I don't think that we are close to providing that capability yet (@jonbob ? @philipwjones ?). Maybe the tool should be applied to the env_mach_pes.xml file?

@rljacob , any suggestions? leave this as a question about the change of behavior (from sometime in the past), asking whether this was intentional? request a tool to examine whether the PE layout is legal and supported? just close?

**Comment by jonbob** [comment]
The partition files are still correctly listed in the corresponding input_data_list files, so I'm not sure what else to do from the MPAS component side. For what it's worth, we have no current plans to generate those partition files on the fly -- especially since the partitioning is moving away from simple metis decompositions.

**Comment by jonbob** [comment]
@worleyph - is it possible to just run check_input_data?

**Comment by worleyph** [comment]
@jonbob - I don't know. I'll give it a try. thanks.

**Comment by worleyph** [comment]
@jonbob and @rljacob , ./check_input_data does the job for me. I guess the only question now is whether to put this (back) into case.setup, so that naive users (like me :-) ) don't have to know to run ./check_input_data to check on the feasibility of a PE layout. We could also just add this to the model documentation (or Peter Caldwell's Confluence page?) on changing the PE layout.

**Comment by rljacob** [comment]
Lets close this.  We'll add running of check_input_data to the documentation.
