### ISSUE TITLE
MPI tag can overflow with multi-instance

### ISSUE THREAD

**Issue by jhkennedy** [E3SM-Project/E3SM#2487]
When using the multi-instance capability on Titan, if the number of instances is `~ 30` the MPI tag overflows, resulting in messages like: 

```
PMPI_Isend(108): Invalid tag, value is 2100105 
20037 Rank 329 [Tue Aug  7 13:22:54 2018] [c4-1c1s3n0] Fatal error in PMPI_Isend: Invalid tag, error stack: 
20038 PMPI_Isend(161): MPI_Isend(buf=0x49eea9f0, count=15, MPI_INTEGER, dest=155, tag=2100105, comm=0xc400020e, requ      est=0x7ffffffe09b0) failed
```

Looking around, it appears `cray_mpich` has a maximum valid tag of `2097151` (or `2^21 -1`). (See similar issues: [lanl/SNAP#6](https://github.com/lanl/SNAP/issues/6), [Nek5000/Nek5000#65](https://github.com/Nek5000/Nek5000/issues/65))

Is it possible to adjust the MPI tags?

**Comment by sarats** [comment]
@jhkennedy Do you know if this is limited to a single call location or ...? I know of some MPI profiling tools if you need to track down the calls. 

On first glance, resetting the tag when it is > MPI_TAG_UB seems like a reasonable idea?

**Comment by jhkennedy** [comment]
@sarats I'm not sure if this is limited to a single call location or a more widespread issue, nothing jumped out at me immediately and I haven't had a chance to do a deep dive yet. Resetting the tag I think is def. the first approach to try and take. 

I'll happily take any of the MPI profiling tool suggestions you have.

**Comment by sarats** [comment]
@jhkennedy I think looking at the case layout and figuring out which component is running on rank 329 or that node could be the first step. Running in debug mode and with a debugger is probably the low effort solution. Can you let me know how to replicate this? 

Thinking more about this, we probably need MPI tracing tool like https://github.com/sstsimulator/sst-dumpi. I tried getting a simple example working on Titan but this seems to miss any useful documentation. Just FYI, mpiP is a good profiler for figuring out communication time distribution but it won't be useful for debugging here.

**Comment by worleyph** [comment]
It might be interesting to try the PR with component task-to-node mapping information. It writes this out per component instance (though I have never actually tested this), so might help identify what is running on rank 329.

**Comment by sarats** [comment]
@jhkennedy Let us know how to replicate. Depending on how complicated this scenario gets, we may resort to writing a MPI wrapper function to identify when tag overflows and print useful debugging info. 

@worleyph You found a customer before the PR is merged ;)

**Comment by jhkennedy** [comment]
@sarats and @worleyph , @PeterCaldwell pointed me to #2231 where the MPI tags were recently adjusted. Reverting #2231 fixes this issue. 

However, I suspect @amametjanov had a good reason to try and avoid MPI tag collision in that PR, so I think the approach to fixing this issue would be to guard the max MPI tag value (`< MPI_TAG_UB`). Any thoughts @amametjanov ?

**Comment by amametjanov** [comment]
@jhkennedy, there is additional info at ESMCI/cime#2363: i.e. hangs in single-instance runs with large number of MPI tasks.

+1 on adding a `< MPI_TAG_UB` guard or using previous tags if running in multi-instance mode (`eci > 1`).

**Comment by jhkennedy** [comment]
Thanks @amametjanov , that's very helpful. 

@rljacob and @jgfouca , should this be done/fixed in ESMCI/cime instead of here? Or both?

**Comment by jgfouca** [comment]
@jhkennedy , ESMCI plz

**Comment by jhkennedy** [comment]
@amametjanov, the tag values currently are set like `msgtag=comp(eci)%cplcompid*10000+eci*10+5`. 

Can you explain to me what the possible `comp(eci)%cplcompid` values are, especially in a multi-instance case? 

I was getting tag values of `2100105` which idicates to me `comp(eci)%cplcompid == 210` in that case, but the other PRs note that the max `cplcompid == 34` for `CPLESP`. Was that just for a single instance case?

**Comment by amametjanov** [comment]
@jhkennedy, the top of e3sm.log should have these values printed by `seq_comm_printcomms`. Could you check what they are in the multi-instance mode?

**Comment by ckoven** [comment]
Hi All-

Just wanted to let you all know that I think I am running into a version of this issue, as reported in https://github.com/ESCOMP/ctsm/issues/515.  For context, what I'm trying to do is a large ensemble of single-point I-compset runs with perturbed CLM parameters in each ensemble member.  In the past, I've been able to do this as a single multi-instance case (with multiple CLM instances only, and single instances of the DATM and stub components) with ~500 ensemble members on Cheyenne, but recently was unable to get more than ~100 ensemble members to work on Edison, with error messages that look very similar to those here.

I just wanted to point out that the proposed solution in https://github.com/ESMCI/cime/pull/2804 of running `--multi-driver` cases above a certain number of instances doesn't appear practical for this particular use-case, at least for now, because the overhead of namelist building for all of the instances of DATM is very high.  I guess I can try to run an ensemble of ensembles, where the innermost ensembles are order ~50 non-multi-driver ninst_lnd cases, and the outermost ensemble members are entirely separate cases, as a solution to the problem I'm running into, but that will require a lot more monitoring to make work. So it would be nice to get back the ability to run these larger ensembles as simple multi-instance cases, if possible.  Anyway, just wanted to bring this up here, and thanks for any guidance you all can offer.

**Comment by jhkennedy** [comment]
This has been fixed, closing.
