### ISSUE TITLE
Missing finidat file for ne30 grid

### ISSUE THREAD

**Issue by singhbalwinder** [E3SM-Project/E3SM#2523]
We recently found that `finidat` file is missing for `ne30` grid for `FC5AV1C-L` compset. I checked `namelist_defaults.xml` in the clm’s bld directory and didn’t find any entry for the `ne30` grid for `finidat`. 
 
This file is very important for running F-cases and fully coupled cases at this resolution. `finidat` file is needed for `ne30` grid for various model configurations (1850, 2000, 20TR, w/wo BGC etc.).

Tagging: @PeterCaldwell , @cameronsmith1 , @polunma  and @philrasch

**Comment by singhbalwinder** [comment]
We had some initial discussion on email and here is a reply from @PeterCaldwell :

> 

> Here’s the clm finidat file for the 1950 low-res compsets Philip and I created:
> lnd/clm2/initdata/clmi.A_WCYCL1950S_CMIP6_LRtunedHR.ne30_oECv3_ICG_simyr1950_c20180316.nc
>  
> Doing an ncdump -h on it reveals this history:
>  
> history = "created on 03/15/18 08:13:34\n",
>                         "03/16/18 08:02:15 gbisht:edison02:interpinic -i /global/cscratch1/sd/pjc/for_Gautam/sample_lnd_ne120_restart/20171208.beta3rc10_H1.ne30_oECv3_ICG.edison.clm2.r.1950-01-01-00000.nc -o ne30_oECv3_ICG.A_WCYCL1950S_CMIP6_LRtunedHR.c706dd419.clm2.r.0001-01-02-00000.nc" ;
>  
> From this I think this file was interpolated by Gautam from the last “historical” simulation done before the low-res DECK was run. Note that it was interpolated from *1950* so it will be inappropriate for use for either 1850 or 1950. I think the appropriate thing to do is to interpolate the clm.r file from the end of the DECK 1850 control run and from year 2000 of the DECK historical run.
>

**Comment by cameronsmith1** [comment]
Hi @singhbalwinder , do the CMIP compsets work?    I haven't used the AV1C compsets for awhile, although I would expect the finidats to still be there.

**Comment by cameronsmith1** [comment]
Hi @singhbalwinder , I am confused.  I don't understand how your comment relates to mine.   I am also not sure why you want to use an AV1C case rather than a CMIP case.   Can you clarify?

**Comment by golaz** [comment]
@singhbalwinder: The CMIP DECK simulations are all using spun-up land initial conditions. For the piControl simulation, we recycled initial conditions from previous control simulations. For the historical coupled simulations, we branched of from piControl. For the AMIP simulations, we branched of from the historical simulations in 1870.

**Comment by singhbalwinder** [comment]
Sorry for my brief and somewhat confusing response. What I meant was that if we launch a test with FC5AV1C-L compset using an ne30 grid, the lnd_in namelist file will not pick up a file for `finidat`. The reason being, there is no `finidat` file mentioned for ne30 grid in the `namelist_defaults.xml` file under `clm/bld/namelist_files`.

The way model works is that it looks for default files (or namelist values) in namelist_defaults.xml file for all the namelist parameters specified in the namelist file (e.g. lnd_in). Model also looks into "use case" file for a particular compset and overrides the values it obtained from namelist_defaults.xml with the values from the use case file. In this case, model looks for `finidat` in namelist_defauls.xml file and couldn't find one for ne30 grid (there is no use case file for FC5AV1C-L in `clm/bld/namelist_files/use_cases`.

Now for CMIP cases, I believe, `finidat` is mentioned in the use case files for CMIP compsets in `clm/bld/namelist_files/use_cases` so it should pick up the right file as you mentioned (I just checked `1850_CMIP6_control.xml` use case file and `finidat` is mentioned in there). Does that make sense? Please let me know if there are still questions. Thanks!

**Comment by singhbalwinder** [comment]
> I am also not sure why you want to use an AV1C case rather than a CMIP case. Can you clarify?

@cameronsmith1 : I use FC5AV1C-L compset for my test model runs as it is the default (and latest) compset for atmosphere model.

**Comment by cameronsmith1** [comment]
Hi @singhbalwinder , I would argue that the CMIP compset should be considered the 'latest' version of the atmosphere model (although it has primarily been used in the coupled configuration).

If you really need to use AV1C-L as a test-case, then I would say that having finidat='' would work for most tests, and is backwards compatible.   If you really really need to use AV1C-L with a spun-up finidat, you could use the ones from the CMIP compset, but then why not use the CMIP compset?

I think the CMIP compset should work for the F-configuration out-of-the-box.   I certainly intended that to be true when I implemented it, although I haven't checked the released version.

The only thing the AV1C-L compsets have that the CMIP compsets are currently missing is a 2000 compset.   It would be easy to create, but it wasn't needed for the CMP simulations.

**Comment by singhbalwinder** [comment]
Thanks @cameronsmith1 . I do not know the CMIP compsets enough to comment. Would you please point me to a CMIP atmospheric compset? Is it some variant (different tuning parameters etc.) of FC5AV1C-L?

Majority of our tests are based on FC5AV1C-L. If CMIP compsets are the one we should be using, we should switch our tests too to CMIP (does that apply to  A_WCYCL* compset as well?). I remember me and @PeterCaldwell have been advising people to use FC5AV1C-L for their projects thinking that it is the "default" or "latest" atmospheric compset. If CMIP compset is the one we should be using, we should probably let others know as well. 

You are right, having `finidat=''` should be fine for small tests but it does make a difference if we run a long simulation and analyse results. Probably it is obvious now but @polunma and I have previously found that `finidat=''` causes the model to produce very different answers as compared to the model with a spun up `finidat`. I know a lot of people are using FC5AV1C-L for production runs and having `finidat=''` will impact their work.

**Comment by singhbalwinder** [comment]
Okay I see `F20TRC5-CMIP6` and `F1850C5-CMIP6` compsets. Like you mentioned, we need to create a 2000 compset for CMIP. I will take a look at the use case files for these compsets to make myself aware of the differences between these and F*C5AV1C-L compsets.

**Comment by PeterCaldwell** [comment]
I agree with @cameronsmith1 that we should use the CMIP6 compsets for all analysis from now on. There are 2 things that compsets give us: initial/boundary conditions and tuning parameters. F*C5AV1C-L is set up to always give us the latest tuning parameters, but it uses older CMIP5-like initial/boundary conditions. The new CMIP6 compsets use the v1 tuning parameters and the latest/greatest boundary/initial condition data. 

As Philip says, there isn't an F2000 CMIP6 compset yet. Dave Bader tends to hate the F2000 compset because it convolves aerosol and GHG changes, so would like to see less reliance on it going forward. That said, F2000 is the scenario that is best observed so I think it still plays a role. 

Thus I think we need to create an F2000 compset. Note that I've already asked @wlin7 to create an F1950 compset for the high-res effort. @cameronsmith1 - is creating an F2000 compset something you could do?

**Comment by singhbalwinder** [comment]
Thanks @PeterCaldwell and @cameronsmith1 . I am glad that we are having this discussion. Once we have the F2000 compset ready, I will switch the nightly tests to this new compset. I will also add tests for other important (F20TR, F1850 etc.) compsets as well.

**Comment by cameronsmith1** [comment]
As @PeterCaldwell mentioned, FC5AV1C-L was supposed to be the latest tuning, but there were some small tuning changes by the Coupled Watercycle Team for the CMIP configuration (@golaz ).

I agree with Dave that we need to be careful about how we use an F2000 case.  I also agree with  @PeterCaldwell that F2000 is still valuable because we have good observations.  It saves a lot of time when doing development and science (10 years of F2000 can save 10 realizations of 150 years of B20TR). 

Yes, I could create an F2000, or other modern compset (@golaz makes a good argument for F2010), however it is not what I am on the hook for under Phase II, so it would mean reprioritizing, and I am not keen on doing that unless there is a compelling need.  These compsets also always take much longer than you expect because there are so many hidden gotchas that must be dealt with.    

BTW, we are also still lacking any future CMIP compset.  That is partly because CMIP hasn't provided all the input data (although most of it is now available) and there is no plan in Phase II to create a future compset that I know of.

**Comment by PeterCaldwell** [comment]
@cameronsmith1  - I agree you shouldn't reprioritize your phase 2 tasks. Having a modern F compset is important though, so I hope someone at the council level makes it *someone's* priority. @singhbalwinder - perhaps you should ask Shaocheng? Or @golaz - perhaps you should ask someone to do this?

**Comment by singhbalwinder** [comment]
I will email Shaocheng about it.
