### ISSUE TITLE
iceberg support broke a high-res case

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#2654]
From looking through old cdash results, it appears that PR #2602 caused the SMS.T62_oRRS30to10v3wLI.GMPAS-IAF.cori-knl_intel  test to fail.

It was passing using master version  0757e202
https://my.cdash.org/viewTest.php?onlypassed&buildid=1551671

Then failed with b0f0d4d (the merge of PR #2602 )
https://my.cdash.org/viewTest.php?onlyfailed&buildid=1553583 

And has not passed since.

**Comment by darincomeau** [comment]
PR #2602 changed the runoff mapping file for the RRS30to10wLI grid.
I think that due to the ocean initial condition for the RRS30to10wLI grid not being properly spun up, the configuration is currently highly susceptible to instability, and this change may have been enough to trigger the instability earlier, causing the test to fail. I noted in the conversation of PR #2602 that:
It is a known issue (#2606) that configurations with the oRRS30to10v3wLI grid without ice shelf melt fluxes fail, which shouldn't impact this PR.
however at the time I hadn't also tested the default configuration with melt fluxes.
I suspect the resolution of issue #2606 will also resolve this issue.
