### ISSUE TITLE
Error with module files during case.setup in cori after down time  

### ISSUE THREAD

**Issue by amrapallig** [E3SM-Project/E3SM#3095]
Many modules have been upgraded for cori after the maintenance and 
E3SM/cime/config/cesm/machines/config_machines.xml has the older versions of those modules that are no longer available for the machine.

For example, the error I got during ./case.setup is
ERROR: module command /opt/modules/default/bin/modulecmd python swap cray-mpich cray-mpich/7.7.0 failed with message:
cray-mpich(3):ERROR:105: Unable to locate a modulefile for 'cray-mpich/7.7.0'

I tried to fix few locally with available default versions of the moduefiles in the following file as mentioned. E3SM/cime/config/cesm/machines/config_machines.xml.
   cray-mpich/7.7.0   to  cray-mpich/7.7.6
   pmi/5.0.13   to   pmi/5.0.14
   craype/2.5.14  to  craype/2.5.18
   PrgEnv-intel/6.0.4  to  PrgEnv-intel/6.0.5
There are still more to fix.

I am getting module error one at a time, during case set up, and I am not sure how many more module files are needed to be fixed.

**Comment by rljacob** [comment]
Work on cori started right after it came back up.  Watch for a PR with fixes.

**Comment by ndkeen** [comment]
Indeed several of the modules we use on Cori were "removed" after the SW maintenance.  In the past, we've been able to use a module "pe_archive" to regain access to the older module versions, however, this one has been removed as well. I asked NERSC about this and I copy/pasted the reply below.

I've started down the path of updating several of our modules to current defaults for Cori.
Most of the tests in e3sm_developer pass, however, any that use MPAS will fail because of an issue with perl modules. The error will indicate a missing `Switch.pm`.  We've run into this before (when first porting to Cori) and I'm not sure exactly what happened to fix the issue for all of us. NERSC refused to install the module in the official perl install and I had resorted to installing my own Perl modules in `/project/projectdirs/acme/perl5`. I suggested other E3SM folks use this solution and it seemed to work, however, because this never came up again, I'm wondering if NERSC _did_ eventually add Switch. The perl modules I installed are still there, but something isn't working and I get a segfault when trying to use XML::LibXML. I'm trying to get around this, but it could be that we need to ask NERSC if they can allow Switch.  I did email them about this in a separate ticket and they suggested we be patient as many software packages need to be rebuilt.

I have also found a GREAT work-around, but it involves changing source in the MPAS framework. Turns out, the Switch module is not adding anything important and it's straight-forward to replace the code that uses this with something that doesn't rely on Switch module at all. I asked @jonbob about making a change like this. I can show others how to make the change (same change in 3 diff perl files).

There are a couple of fails in the e3sm_developer suite, but they appear to NOT be related to the module version differences directly. 

I can create a PR to update the modules and get things working better than it was. Or wait until we can do it all?

```
from NERSC:

With the new CLE7 OS upgrade, and older libraries not working (although some still do), we do not expect to provide the pe_archive module to make the older software available to run on Cori (and yes, we told users to try the CLE6 module files, but those will only try to find the libraries still existing in the normal /opt/intel and /global/common/cori/software locations, and just fail if not found. They won't get access to the older libraries that are already removed on our system, yet we archived to a place where pe_archive points to).
 
The list of PE changes and details about which modules are default, new, and removed can be found at:
https://www.nersc.gov/users/computational-systems/cori/updates-and-status/programming-environment-change-on-cori-in-july-2019/
(this link has been announced in many recent weekly emails from Rebecca and the last night's message from me after Cori returns after the OS upgrade)
```

**Comment by ndkeen** [comment]
Regarding Perl modules.  Using this tester:

```
#! /usr/bin/perl

use strict; 
use warnings;
use XML::LibXML;
use Switch;

1;
```

```
cori02% ./xml-switch.pl 
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /usr/lib/perl5/site_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.26.1 /usr/lib/perl5/vendor_perl/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.26.1 /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi /usr/lib/perl5/5.26.1 /usr/lib/perl5/site_perl) at ./xml-switch.pl line 6.
BEGIN failed--compilation aborted at ./xml-switch.pl line 6.
```

And then if I try to use some previous Perl modules.

```
cori02% setenv PERL_LOCAL_LIB_ROOT "/project/projectdirs/acme/perl5"
cori02% setenv PERL5LIB "/project/projectdirs/acme/perl5/lib/perl5/x86_64-linux-thread-multi:/project/projectdirs/acme/perl5/lib/perl5"

cori02% ./xml-switch.pl 
Segmentation fault

Which gets past the Switch, but stops on the use XML::LibXML
```

**Comment by ndkeen** [comment]
This branch can be tried: `ndk/machinefiles/cori-july2019-upgrade`

And then possibly need to add these env variables to local set to get around the Switch error:

```
Add, say, in .cshrc.ext:

  setenv PERL_LOCAL_LIB_ROOT "/project/projectdirs/acme/perl5"
  setenv PERL5LIB "/project/projectdirs/acme/perl5/lib/perl5/x86_64-linux-thread-multi:/project/projectdirs/acme/perl5/lib/perl5"
```

**Comment by ndkeen** [comment]
Documenting this here for now.

I'm seeing some potential odd behavior -- so this could be the machine acting up. Some of the runs after this change (I'm talking about master and maint-1.0) are timing out after running much longer than anticipated.  In the past, we've had to deal with some from of "hanging" and I have reason to believe it's related to IO -- as we are updating the netcdf/hdf modules.

With these same module changes on maint-1.0, I've found that the fails are more repeatable (still trying to test more) and that updating the module versions one step higher (above defaults) the problems go away. Additionally, a few of the tests run a little quicker.

Currently I have:
```
cray-netcdf-hdf5parallel/4.6.1.3
cray-hdf5-parallel/1.10.2.0
cray-parallel-netcdf/1.8.1.4
```

And when I update to higher versions, I'm trying:
```
      cray-netcdf-hdf5parallel/4.6.3.0
      cray-hdf5-parallel/1.10.5.0
      cray-parallel-netcdf/1.11.1.0
```

**Comment by rljacob** [comment]
MOTD re: cori and I/O:   

> 08/01/19 15:00 PDT - NA. Update by Aug 07 17:00 PDT. System in degraded mode. 
> Cori continues to experience degraded performance on the global home, global project, global common, cscratch1 and cvmfs file systems. Engineers are working with Cray to correct the problem..
