### ISSUE TITLE
ERP_Ln5.ne30_ne30.FC5AV1C-L.compy_intel is failing

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#3229]
Error message at end of atm.log in "case2" phase of test is:

```
 nstep=          27  time=  9.375000000000000E-002  [day]
SHR_REPROSUM_CALC: Input contains  0.12000E+02 NaNs and  0.00000E+00 INFs on process       0
 ERROR: shr_reprosum_calc ERROR: NaNs or INFs in input
```

This test is part of the e3sm_extra_coverage suite run with master on compy.

This suite used to run on sandiatoss3 but we moved it to compy so problems could be debugged.  The same test was failing there (but passed at one point).  See #2614

**Comment by singhbalwinder** [comment]
Thanks for the info. I will look into it.

**Comment by singhbalwinder** [comment]
Probably we already know this but I would like to record here that `ERP_Ln5.ne4_ne4.FC5AV1C-L.compy_intel` works. My ne30 run is waiting in queue.

**Comment by singhbalwinder** [comment]
I think I now know what is going on with this test. The NaNs are coming from `radheat_tend` subroutine in `radheat.F90` as `fsns, fsnt, flns` and  `flnt` are all NaNs in the restart run of ERP. In this ERP test, we run the model for 3 time steps and then restart it to run from 4th to 5th time step. This restarted run output is then compared with the non-restart 5 time step run.

From my reading of the code, they are NaNs as radiation is invoked every other time step. For example, radiation is invoked at time steps 1st, 3rd, 5th and so on. In a normal (e.g. non-restart) run, variables  `fsns, fsnt, flns` and  `flnt` retain their values on 2nd, 4th and so on time steps as they are all intent  in-outs. When a run restarts at time step 4, the radiation codes are not invoked so variables  `fsns, fsnt, flns` and  `flnt` do not get any values from radiation and are NaNs when accessed in `radheat_tend` subroutine.

One solution would be to put these variables in the restart file so that they are read when we restart the model.

**Comment by singhbalwinder** [comment]
I am not sure how this test passes for ne4. I will try to look into this more carefully.

**Comment by singhbalwinder** [comment]
It looks like radiation is called every time step when we use ne4 as the time step for ne4 is 2 hours (7200 sec). ne30 simulations has a time step of 1800s.

As we call radiation every time step, variables `fsns, fsnt, flns` and `flnt` get new values every time step.

**Comment by rljacob** [comment]
Nice detective work!  So 5 steps is a bad value for this test at that resolution.   Please find one that works and update the test.

**Comment by singhbalwinder** [comment]
Thanks @rljacob ! If we run for 7 time steps, it works (`ERP_Ln7.ne30_ne30.FC5AV1C-L`). I can make that change but I think we should fix it as we might run into it again. In theory, restarts should not depend on after how many time steps we restart the model. 

Are there any other known cases where we do not expect restart to work? Few years back, we had an issue where model was not able to restart mid month. I think that was fixed but I am not sure about that. @mt5555 might know more about that issue.

If you also think that it is important to fix this issue, I can work with the developers to come up with a fix. In the meantime, I will just update this test so that we can use it in our nightly tests.

**Comment by rljacob** [comment]
If restarts should work for any run length then yes fix that.  I don't know of other cases.  Yes update the test in the meantime.

**Comment by golaz** [comment]
@singhbalwinder : interesting discovery. I'm surprised this wasn't uncovered before.

If we want to really support having restart capability at any time-step, then we should fix it. But I would be fine if we decided to be more restrictive and only supported restarts during radiation time-steps. In that case, the model should stop with an error when it's restarting on a non-radiation time step.

**Comment by PeterCaldwell** [comment]
Good find! I'd rather not add *more* variables to our restart files since they are already 3 TB at ne1024 and writing them is already bringing us to our knees. I agree with Chris G that issuing an error when we try to restart on non-rad timesteps is a good idea.

As an aside (which doesn't need to be addressed) - I'm surprised fsns, fsnt, flns, and flnt are used in radheat_tend. I would have expected surface and TOA variables to only be used for output and *3d* radiative fluxes or 3d radiative heating tendencies to be what the model actually uses for timestepping. If you git blame the lines that need fsns, do you see that this was a change someone made recently? Like Chris, it surprises me that this has existed for a long time without anyone noticing.

**Comment by singhbalwinder** [comment]
Thanks @golaz and @PeterCaldwell . Following @PeterCaldwell suggestion, I looked through the codes and found out that [this](https://github.com/E3SM-Project/E3SM/commit/38626706681a00d80178b6f090e5cef2bee81143#diff-f862e0dfeb1061e7bff16074cfb68801) commit changed the code to remove these fluxes (flnt, fsnt etc.) from `pbuf`. Variables in `pbuf` with `global` attribute are stored in the restart file. As they now do not exist in `pbuf`, they are not stored in the restart files and we see this error.

If my above analysis is correct, I think that also clears the confusion I had about this test that it used to work when we originally added it few years back. I was confused as to why it is not working now.

I can add the fix which @golaz suggested but do we still want to add it given the info above?

**Comment by rljacob** [comment]
PR #3237 allowed this to pass on compy_intel.
