### ISSUE TITLE
Automated selection of pcols in EAM

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/E3SM#3485]
@worleyph has run a number of very nice, comprehensive experiments showing that specifying pcols acccording to certain considerations can give meaningful speedup in the EAM physics. See [here](https://acme-climate.atlassian.net/wiki/spaces/EPG/pages/1098778304/Performance+impact+of+optimizing+PCOLS+for+ne30+and+ne30pg2+physics+mesh+resolution) for a description of the experiments. See the top of [this page](https://acme-climate.atlassian.net/wiki/spaces/COM/pages/1112047753/Physgrid+v2+integration+ne30pg2+r05+oECv3) for instructions to manually specify pcols for two compsets of interest. Now that the performance gain is established, it would be useful for the optimal pcols to be calculated automatically.

**Comment by worleyph** [comment]
@ambrad , FYI, I spent the last couple of days seeing whether I could replace the compile-time setting of pcols with a runtime option. This now appears to be working (with very limited testing, so still may not be acceptable). 

Back in the earlier 2000's, I ran experiments that convinced me that setting the first dimension of the chunk data structure at compile-time allowed the compiler to generate more performance-efficient code, and this motivated this design choice in CAM. However, CAM/EAM has evolved significantly since then, and, for example, phys_grid now uses psetcols to define this first dimension, and the compiler never sees a compile-time parameter.  So PCOLS likely no longer serves a purpose.

I was concerned that compile-time PCOLS was too baked into the code to be easily backed out, but have been pleasantly surprised so far. (@oksanaguba will be unhappy as it requires even more allocate/deallocate logic, but perhaps this can still be minimzed in a future clean-up step). I still need to verify that my changes do not degrade performance. However, if true, then the selection of pcols can be done within EAM (and not in CIME) and probably more effectively. The idea is still to have the same declared first dimension over all chunks. (Allowing this instead to vary per chunk is not something that I have thought about, and am not sure whether it is doable or is even worth doing.)

**Comment by worleyph** [comment]
@ambrad (and @mt5555  ), I tried rerunning my pcols-optimization benchmark case

     -res ne30pg2_ne30pg2 -compset FC5AV1C-L 

from last December using current master, and it failed with:

      NC_FORMAT_NETCDF4 is not yet supported

when trying to read 

     /compyfs/inputdata/atm/cam/chem/trop_mam/atmsrf_ne30pg2_200129.nc

I looked at the old atm_in, and it differed from the new one with

     15c15
     <  bnd_topo		= '/compyfs/inputdata/atm/cam/topo/USGS-gtopo30_ne30pg2_16xdel2-PFC-consistentSGH.c20190417.nc'
     ---
     >  bnd_topo		= '/compyfs/inputdata/atm/cam/topo/USGS-gtopo30_ne30np4pg2_16xdel2.c20200108.nc'
     32c32
     <  drydep_srf_file		= '/compyfs/inputdata/atm/cam/chem/trop_mam/atmsrf_ne30np4_110920.nc'
     ---
     >  drydep_srf_file		= '/compyfs/inputdata/atm/cam/chem/trop_mam/atmsrf_ne30pg2_200129.nc'

Should I try again with the old setting for  bnd_topo and drydep_srf_file, or is there some PIO magic that I can use instead?

**Comment by rljacob** [comment]
You can set PIO_TYPENAME to netcdf.  Why are netcdf4 files being introduced in to pg2 compsets?  That should not happen.

**Comment by ambrad** [comment]
That's my fault. I"ll fix the files and check the others. The map files should be fine because the script includes 3 as part of the process, but the atmsrf script does not.

**Comment by worleyph** [comment]
@ambrad , thanks. Please tell me when you have finished, and I'll resubmit my jobs then.

**Comment by ambrad** [comment]
@worleyph I fixed the atmsrf file on the blues input server and on compy. I also checked the map and domain files, and they are fine. Thanks for reporting the issue.

**Comment by worleyph** [comment]
@ambrad, will this then work on Cori-KNL as well? Thanks

**Comment by ambrad** [comment]
Good point. I just fixed it. If you hit a problem on another machine, just delete `inputdata/atm/cam/chem/trop_mam/atmsrf_ne30pg2_200129.nc` so that it can auto-download again from Anvil's inputdata server, where the master corrected file lives.
