### ISSUE TITLE
case.build --use-old

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#3769]
Case created with `./cime/scripts/create_test SMS.ne4_ne4.FC5AV1C-L` with latest master is running into error with `case.build --use-old`:
```
azamat@blueslogin4:SMS.ne4_ne4.FC5AV1C-L.anvil_intel.20200813_105247_2q1j5j$ tail -n 2 bld/e3sm.bldlog.200813-105654 
gmake: *** No rule to make target `/lcrc/group/acme/azamat/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.20200813_105247_2q1j5j/bld/lib/libocn.a', 
needed by `/lcrc/group/acme/azamat/acme_scratch/anvil/SMS.ne4_ne4.FC5AV1C-L.anvil_intel.20200813_105247_2q1j5j/bld/e3sm.exe'.  Stop.
gmake: *** Waiting for unfinished jobs....
```

**Comment by jonbob** [comment]
Any update? Many of us use this for debugging and other situations

**Comment by akturner** [comment]
@jgfouca: Is there any update with this? I use this build method and am currently dead in the water.

**Comment by rljacob** [comment]
We aren't going to support --old-build forever.    What needs to be added/changed in the cmake system for it to be useful in your workflow?

**Comment by jgfouca** [comment]
@amametjanov , @jonbob , @akturner , the `--use-old` option was intended to be an emergency fallback option that I felt was necessary due to the magnitude of the changes that were needed to move the build system to cmake. I wanted people to have something immediately available in case there was an unforeseen problem new system. The intent was not to support two build systems indefinitely. If people are still needing to use the old system due to some deficiency with the new system, I'd like to hear about that deficiency so it can be fixed and we can move forward.

**Comment by akturner** [comment]
Hi, Better error messaging would be useful as at the moment any error is completely incomprehensible to me. Take the below error message  as an example (in the bld e3sm.log) - it took several hours to even determine which CMakeLists.txt/ or cmake/build_model.cmake file is referenced. After another several hours trying to understand the errors I'm no closer to understanding what the problem is. I wanted to use the old system as when there were errors there it was much easier to understand the source of issues. 

Configuring with cmake cmd:
cmake -DCIME_MODEL=e3sm  -Dcompile_threaded=FALSE  -DINSTALL_SHAREDPATH=/home/akt/projects/acme/scratch/dtestcase/bld/gnu/openmpi/nodebug/nothreads/mct  -DUSE_KOKKOS=FALSE 
 -DCOMP_NAMES='cpl;datm;slnd;mpassi;docn;drof;sglc;swav;siac;sesp' -DCASEROOT="/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/scripts/dtestcase" -DCASETOOLS="
/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/scripts/dtestcase/Tools" -DCIMEROOT="/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime" -DCOMP_INTER
FACE="mct" -DCOMPILER="gnu" -DDEBUG="FALSE" -DEXEROOT="/home/akt/projects/acme/scratch/dtestcase/bld" -DINCROOT="/home/akt/projects/acme/scratch/dtestcase/bld/lib/include" 
-DLIBROOT="/home/akt/projects/acme/scratch/dtestcase/bld/lib" -DMACH="linux-generic" -DMPILIB="openmpi" -DNINST_VALUE="c1a1l1i1o1r1g1w1i1e1" -DOS="LINUX" -DPIO_VERSION="2" 
-DSHAREDLIBROOT="/home/akt/projects/acme/scratch/dtestcase/bld" -DSMP_PRESENT="FALSE" -DUSE_ESMF_LIB="FALSE" -DUSE_MOAB="FALSE" -DCOMP_LND="slnd" -DCOMPARE_TO_NUOPC="FALSE"
 -DUSE_TRILINOS="FALSE" -DUSE_ALBANY="FALSE" -DUSE_PETSC="FALSE"  -DCMAKE_C_COMPILER_WORKS=1 -DCMAKE_CXX_COMPILER_WORKS=1 -DCMAKE_Fortran_COMPILER_WORKS=1  /home/akt/Work/E
3SM/feature_branches/initial_build/E3SM/components

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The Fortran compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/mpif90 supports Fortran 90
-- Checking whether /usr/bin/mpif90 supports Fortran 90 -- yes
Found MPAS component ice model 'mpassi'
-- *** Building MPAS tools from source ***
You have called ADD_LIBRARY for library common without any source files. This typically indicates a problem with your CMakeLists.txt file
You have called ADD_LIBRARY for library ice without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component atm model 'datm'
You have called ADD_LIBRARY for library atm without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component lnd model 'slnd'
You have called ADD_LIBRARY for library lnd without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component ocn model 'docn'
You have called ADD_LIBRARY for library ocn without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component rof model 'drof'
You have called ADD_LIBRARY for library rof without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component glc model 'sglc'
You have called ADD_LIBRARY for library glc without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component wav model 'swav'
You have called ADD_LIBRARY for library wav without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component iac model 'siac'
You have called ADD_LIBRARY for library iac without any source files. This typically indicates a problem with your CMakeLists.txt file
Found component esp model 'sesp'
You have called ADD_LIBRARY for library esp without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at cmake/build_model.cmake:226 (add_executable):
  add_executable called with incorrect number of arguments
Call Stack (most recent call first):
  cmake/cpl/CMakeLists.txt:1 (build_model)


CMake Error at cmake/build_model.cmake:227 (target_sources):
  Cannot specify sources for target "e3sm.exe" which is not built by this
  project.
Call Stack (most recent call first):
  cmake/cpl/CMakeLists.txt:1 (build_model)


CMake Error at cmake/build_model.cmake:232 (target_link_libraries):
  Cannot specify link libraries for target "e3sm.exe" which is not built by
  this project.
Call Stack (most recent call first):
  cmake/cpl/CMakeLists.txt:1 (build_model)


-- Configuring incomplete, errors occurred!
See also "/home/akt/projects/acme/scratch/dtestcase/bld/cmake-bld/CMakeFiles/CMakeOutput.log".

**Comment by worleyph** [comment]
Also, see discussion in issue #3586  and in issue #3758  for capabilities that went missing in the move to CMake.

**Comment by worleyph** [comment]
Sorry, #3586 was resolved/

**Comment by akturner** [comment]
As another example at the e3sm build stage I get the following error - I cannot for th elife of me figure out where in the build system this build command is being built by Cmake:

'''
[100%] Linking Fortran executable /home/akt/projects/acme/scratch/dtestcase/bld/e3sm.exe
cd /home/akt/projects/acme/scratch/dtestcase/bld/cmake-bld/cmake/cpl && /snap/cmake/599/bin/cmake -E cmake_link_script CMakeFiles/e3sm.exe.dir/link.txt --verbose=1
/usr/bin/mpif90 CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/cime_comp_mod.F90.o CMakeFiles/e3sm.exe.dir/home/ak
t/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/cime_driver.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/c
ime/src/drivers/mct/main/component_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/component_type_mod.F90
.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/cplcomp_exchange_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work
/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/map_glc2lnd_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cim
e/src/drivers/mct/main/map_lnd2glc_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/map_lnd2rof_irrig_mod.
F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/mrg_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feat
ure_branches/initial_build/E3SM/cime/src/drivers/mct/main/prep_aoflux_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/driv
ers/mct/main/prep_atm_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/prep_glc_mod.F90.o CMakeFiles/e3sm.
exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/prep_iac_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/init
ial_build/E3SM/cime/src/drivers/mct/main/prep_ice_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/prep_ln
d_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/prep_ocn_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Wor
k/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/prep_rof_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/
src/drivers/mct/main/prep_wav_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/seq_diag_mct.F90.o CMakeFil
es/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/seq_domain_mct.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_bra
nches/initial_build/E3SM/cime/src/drivers/mct/main/seq_flux_mct.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/ma
in/seq_frac_mct.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/seq_hist_mod.F90.o CMakeFiles/e3sm.exe.dir/ho
me/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/seq_io_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3
SM/cime/src/drivers/mct/main/seq_map_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/seq_map_type_mod.F90
.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/feature_branches/initial_build/E3SM/cime/src/drivers/mct/main/seq_rest_mod.F90.o CMakeFiles/e3sm.exe.dir/home/akt/Work/E3SM/fe
ature_branches/initial_build/E3SM/cime/src/drivers/mct/main/t_driver_timers_mod.F90.o -o /home/akt/projects/acme/scratch/dtestcase/bld/e3sm.exe  ../atm/libatm.a ../lnd/libl
nd.a ../../mpas-source/src/libice.a ../ocn/libocn.a ../rof/librof.a ../glc/libglc.a ../wav/libwav.a ../iac/libiac.a ../esp/libesp.a /home/akt/projects/acme/scratch/dtestcas
e/bld/gnu/openmpi/nodebug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/lib/libcsm_share.a /home/akt/projects/acme/scratch/dtestcase/bld/gnu/openmpi/nodebug/nothreads/mct/l
ib/libmct.a /home/akt/projects/acme/scratch/dtestcase/bld/gnu/openmpi/nodebug/nothreads/mct/lib/libmpeu.a /home/akt/projects/acme/scratch/dtestcase/bld/gnu/openmpi/nodebug/
nothreads/mct/lib/libpiof.a /home/akt/projects/acme/scratch/dtestcase/bld/gnu/openmpi/nodebug/nothreads/mct/lib/libpioc.a /home/akt/projects/acme/scratch/dtestcase/bld/gnu/
openmpi/nodebug/nothreads/mct/lib/libgptl.a -L/home/akt/Work/libraries/netcdf-fortran/netcdf-fortran-4.5.3/gcc/7.5/lib -lnetcdff 
/usr/bin/ld: /home/akt/projects/acme/scratch/dtestcase/bld/gnu/openmpi/nodebug/nothreads/mct/lib/libpioc.a(pio_getput_int.c.o): undefined reference to symbol 'nc_get_att_do
uble'
/home/akt/Work/libraries/netcdf-c/netcdf-c-4.7.4/gcc/7.5/lib/libnetcdf.so.18: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
cmake/cpl/CMakeFiles/e3sm.exe.dir/build.make:525: recipe for target '/home/akt/projects/acme/scratch/dtestcase/bld/e3sm.exe' failed
gmake[2]: *** [/home/akt/projects/acme/scratch/dtestcase/bld/e3sm.exe] Error 1
gmake[2]: Leaving directory '/home/akt/projects/acme/scratch/dtestcase/bld/cmake-bld'
CMakeFiles/Makefile2:718: recipe for target 'cmake/cpl/CMakeFiles/e3sm.exe.dir/all' failed
gmake[1]: *** [cmake/cpl/CMakeFiles/e3sm.exe.dir/all] Error 2
gmake[1]: Leaving directory '/home/akt/projects/acme/scratch/dtestcase/bld/cmake-bld'
Makefile:105: recipe for target 'all' failed
gmake: *** [all] Error 2
'''

**Comment by akturner** [comment]
It would be useful for the error messages to make clear what (Cmake) file generated them.

**Comment by jonbob** [comment]
The fact that this many of our developers feel strongly about having the --use-old as an option should say plenty

**Comment by jgfouca** [comment]
Thanks for the feedback. Lets use this issue as a place to gather items on the build system. I should have time to do a significant update of the build system in the next couple weeks. Hopefully, we can get to a place where `--use-old` can be removed soon.
