### ISSUE TITLE
Optimal filetype for netcdf file in inputdata

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3887]
While not an issue with the code, a github issue is nice place to discuss.

With ne1024 run, I noticed we see a warning in e3sm.log:

```
0: PIO: WARNING: Opening file (/projects/ccsm/acme/inputdata/atm/cam/sst/sst_ifs_360x720_20200110_20200305_c200505.nc) with iotype=1 (PIO_IOTYPE_PNETCDF) failed (ierr=-128, NetCDF: Attempt to use feature that was not turned on when netCDF was built.). Retrying with iotype=PIO_IOTYPE_NETCDF
0: PIO: WARNING: Opening file (/projects/ccsm/acme/inputdata/atm/cam/sst/sst_ifs_360x720_20200110_20200305_c200505.nc) with iotype=1 (PIO_IOTYPE_PNETCDF) failed. But retrying with iotype PIO_IOTYPE_NETCDF was successful. Switching iotype to PIO_IOTYPE_NETCDF for this file 
```

On both Theta and Cori, the filetype is `netCDF-4`

```
thetalogin5% ncdump -k /projects/ccsm/acme/inputdata/atm/cam/sst/sst_ifs_360x720_20200110_20200305_c200505.nc
netCDF-4

cori11% ncdump -k /global/cfs/cdirs/e3sm/inputdata/atm/cam/sst/sst_ifs_360x720_20200110_20200305_c200505.nc
netCDF-4
```

@jayeshkrishna noted that because the file is netcdf4 and PnetCDF does not support NetCDF4 files, Scorpio will use NetCDF instead. He also suggested we should consider converting this file (and others?) to a different filetype.
Something along the lines of:

`ncks -3 in.nc out.nc`

and perhaps add attribute to note that file is same, only changing type.  

Tagging @crterai 

Same issue with a file in ne256 run:
`/global/cfs/cdirs/e3sm/inputdata/atm/cam/sst/sst_ifs_360x720_20200110_20200305_c200505.nc`

**Comment by jayeshkrishna** [comment]
Also tagging @sarich (What is the process that you followed for the file conversions? https://acme-climate.atlassian.net/wiki/spaces/EIDMG/pages/921436224/Netcdf+file+conversion)

**Comment by ambrad** [comment]
Good catch, Noel. For others creating these files, see [this Confluence page](https://acme-climate.atlassian.net/wiki/spaces/ED/pages/1007223420/NetCDF+explainer) for details on NetCDF types used in E3SM. Current policy requires NetCDF3 format and disallows NetCDF4, as I have learned the hard way ;). The line provided above, `ncks -3 in.nc out.nc`, is exactly the right thing to do to convert the files. For large files, I believe `-5` rather than `-3` should be used to create the 64-bit offset format, which is still NetCDF3. The conversion should be done on the inputdata server's file. If the file has propagated to machines, delete the file from the machine's local inputdata directory and let the next simulation re-download the file.

**Comment by mt5555** [comment]
adding one more confluence link on this topic:

Picking a netcdf type for all input files
https://acme-climate.atlassian.net/wiki/spaces/EIDMG/pages/769130507/Picking+a+netcdf+type+for+all+input+files

**Comment by rljacob** [comment]
If the nc4 file has been referred to in code on master (in a use case), the nc3 version should be given a new datestamp in its name and the use cases updated to refer to it (with a PR). That's the only way to make sure the correct file is propagated to all input dirs.

**Comment by crterai** [comment]
Thanks for pointing this out, @ndkeen. Okay, I'll convert the netcdf files to netcdf-3 (with new datestamps) and update the compsets to point to the new netcdf files then.

**Comment by crterai** [comment]
I've converted and created new SST files into netcdf classic (netcdf3) and created the above PR in the SCREAM code base to point to the updated files.

**Comment by ndkeen** [comment]
Closing as @crterai PR fixes
