### ISSUE TITLE
PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF fails on compy

### ISSUE THREAD

**Issue by jonbob** [E3SM-Project/E3SM#3958]
The extra_coverage testing suite, which runs once a week, shows that this test has been failing since early September but passed before that. I ran some additional tests that indicate [PR #3825](https://github.com/E3SM-Project/E3SM/pull/3825) is responsible for introducing the failure. Also note that PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF.compy passes, so the problem appears to be in the ice shelf melt flux code.

**Comment by ndkeen** [comment]
Note I ran this on cori-knl with GNU and it failed in case2run, but the error message is not useful. It ran out of memory when I tried it without P480 and intel, so I'm running again with P480.

The test case with GNU:
`/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/m49-nov19/PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_gnu.r01gnu`

**Comment by jonbob** [comment]
Thanks @ndkeen -- please let me know what happens with your test

**Comment by ndkeen** [comment]
The test with intel completes both runs, but fails the compare.

`/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/m49-nov19/PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel.r00`

**Comment by ndkeen** [comment]
I also tried this test `PEM_P480x1_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-knl_intel` and that also failed.  So it's not the threading.

**Comment by jonbob** [comment]
@mark-petersen - can you take a look at this? Or is it something we need to ask Luke about? The cryo group wants to start tests soon and this needs to be resolved first

**Comment by jonbob** [comment]
This test passes when redi is off, but still fails when GM is off (but redi is on). So the issue appears to be in the redi code

**Comment by mark-petersen** [comment]
Thanks for the background information. I'm testing things now...

**Comment by jonbob** [comment]
Also fails with redi on but redi_k33 disabled

**Comment by mark-petersen** [comment]
I tested QU240 with ice shelves, with melt fluxes on and Redi on, passes partition tests both with the current head, and right after merge for #3825. That makes it harder to find the bug.

I am suspicious of this change in  PR #3825, because surface fluxes are only tested in E3SM:
https://github.com/MPAS-Dev/MPAS-Model/pull/690/files#diff-8095f6b5d5976cc3adcbbbea7455b974cf97a7364ba7062622349fd58b322002R1542

@jonbob could you run the same PEM test with those lines off? It was originally protected by a flag `config_cvmix_use_kpp_buoyancyForcing_fix`, but on the current head, it would be here:
```
src/core_ocean/shared/mpas_ocn_diagnostics.F:
1977      nonLocalSurfaceTracerFlux(indexTempFlux, iCell) = activeTracersSurfaceFlux(indexTempFlux,iCell) &
1978                  + penetrativeTemperatureFlux(iCell) - penetrativeTemperatureFluxOBL(iCell)  &
1979              - fracAbsorbed * (rainFlux(iCell) + evaporationFlux(iCell)) * activeTracers(indexTempFlux,1,iCell)/rho_sw &
1980              - fracAbsorbedRunoff * surfaceThicknessFluxRunoff(iCell)* min(activeTracers(indexTempFlux,1,iCell),0.0_RKIND)/rho_sw !&
1981    !         - fracAbsorbed * (seaIceFreshWaterFlux(iCell) + icebergFreshWaterFlux(iCell)) * &
1982    !         ocn_freezing_temperature( activeTracers(indexSaltFlux, 1, iCell), pressure=0.0_RKIND, inLandIceCavity=.false.)&
1983    !            / rho_sw
```
note line 1980 has `!&` for the continuation.

Note `inLandIceCavity=.false.` looks suspicious here, but there should be no sea ice and ice berg fluxes below ice shelves, which explains that choice.

This does not explain why it is bfb with Redi off, but maybe it interacts. I'll look closer at Redi now.

**Comment by jonbob** [comment]
That line looked suspicious to me as well -- I had tried running with config_cvmix_use_kpp_buoyancyforcing_fix set to false based on this PR, but I didn't check to make sure that the suspicious coding was still protected by it. Checking now, it is still wrapped by that flag in my version:
````
        if(config_cvmix_use_kpp_buoyancyForcing_fix) then
            nonLocalSurfaceTracerFlux(indexTempFlux, iCell) = nonLocalSurfaceTracerFlux(indexTempFlux, iCell) &
               - fracAbsorbed * (seaIceFreshWaterFlux(iCell) + icebergFreshWaterFlux(iCell)) * &
                 ocn_freezing_temperature( activeTracers(indexSaltFlux, 1, iCell), pressure=0.0_RKIND, inLandIceCavity=.false.)&
                  / rho_sw
         endif
````
So I did try that

**Comment by jonbob** [comment]
I'll try the QU240 as well in the coupled model

**Comment by jonbob** [comment]
The QU240 configuration with DIB and ISMF does not appear to be supported

**Comment by mark-petersen** [comment]
I must admit I'm puzzled. The possible code changes are very small, because most are protected by `if (config_use_GM) then` at [line 455](https://github.com/MPAS-Dev/MPAS-Model/compare/b61d423d2048729f7306ea9288479b005496c7ee...7e32f8e80c034acb6f4afb65ce85ce29f33fae0f#diff-4017a051b6d1f951921a78b626f7ec04eb2064089d00473fcfc41a4a493e8ce9R455). The only thing that remains is lines [400](https://github.com/MPAS-Dev/MPAS-Model/compare/b61d423d2048729f7306ea9288479b005496c7ee...7e32f8e80c034acb6f4afb65ce85ce29f33fae0f#diff-4017a051b6d1f951921a78b626f7ec04eb2064089d00473fcfc41a4a493e8ce9L400)-[425](https://github.com/MPAS-Dev/MPAS-Model/compare/b61d423d2048729f7306ea9288479b005496c7ee...7e32f8e80c034acb6f4afb65ce85ce29f33fae0f#diff-4017a051b6d1f951921a78b626f7ec04eb2064089d00473fcfc41a4a493e8ce9L425), which mostly only involves k33, so I'm still puzzled. But at least it is something to try.

@jonbob could you take your version that fails the PEM and replace lines 400-425 with the old version? Here is the original block (from MPAS-Model 769791fe), if it is helpful:
```
               ! Griffies 1998 eqn 34
               if (k > 1) then
                  k33(k, iCell) = k33(k, iCell) + slopeTaperUp*sfcTaperUp* &
                                  areaEdge*dzTop(k)*slopeTriadUp(k, iCellSelf, iEdge)**2
                  k33Norm(k) = k33Norm(k) + areaEdge*dzTop(k)
               end if

               !Taper Redi by tapering the slopes
               k33(k + 1, iCell) = k33(k + 1, iCell) + slopeTaperDown*sfcTaperDown* &
                                   areaEdge*dzTop(k + 1)*slopeTriadDown(k, iCellSelf, iEdge)**2
               k33Norm(k + 1) = k33Norm(k + 1) + areaEdge*dzTop(k + 1)

               slopeTriadUp(k, iCellSelf, iEdge) = &
                  slopeTaperUp*sfcTaperUp*slopeTriadUp(k, iCellSelf, iEdge)
               slopeTriadDown(k, iCellSelf, iEdge) = &
                  slopeTaperDown*sfcTaperDown*slopeTriadDown(k, iCellSelf, iEdge)

            end do ! maxLevelEdgeTop(iEdge)
         end do ! nEdgesOnCell(iCell)

         ! Normalize k33
         do k = 2, maxLevelCell(iCell)
            k33(k, iCell) = k33(k, iCell)/k33Norm(k)*RediKappaSfcTaper(k, iCell)* &
                            RediKappaScaling(k, iCell)
         end do
```

**Comment by jonbob** [comment]
@mark-petersen - it still fails with that code copied in

**Comment by mark-petersen** [comment]
FYI, I'm able to reproduce before/after PASS/FAIL in E3SM, will debug from here...

**Comment by mark-petersen** [comment]
@jonbob said:
> This test passes when redi is off, but still fails when GM is off (but redi is on). So the issue appears to be in the redi code

That is what I thought too, but it must be in the GM part of the code. To summarize the tests, which I confirmed with `PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF`:
1. before #3825, Redi on, GM on: PASS (default settings)
1. before #3825, Redi on, GM off: FAIL
1. after #3825, Redi on, GM on: FAIL (default settings)
1. after #3825, Redi on, GM off: FAIL
1. after #3825, Redi off, GM on: PASS

Since (2) failed, (4) provides no information. The change from (1) to (3) definitely happens in the GM part of the code that changed in #3825. I've tried a bunch of things - expanding all halos, correcting some thread private variables, trying to replace smaller blocks of code - but nothing produces a pass so far.

I'm still working on it, but have other meetings today.

**Comment by vanroekel** [comment]
> he change from (1) to (3) definitely happens in the GM part of the code that changed in #3825. I've tried a bunch of things - expanding all halos, correcting some thread private variables, trying to replace smaller blocks of code - but nothing produces a pass so far.

@mark-petersen can you explain what you mean here?  Do you mean the redi code that lives in ```mpas_ocn_gm.F```?  This seems right given (5) or are you suggesting some interaction with redi and GM on?

**Comment by jonbob** [comment]
@mark-petersen - any luck with this? We had a similar problem in July [(Issue #3719](https://github.com/E3SM-Project/E3SM/issues/3719))

**Comment by mark-petersen** [comment]
I just tested with today's master, 5cef5558c and 
```
./create_test PEM_P480_Ld5.T62_oEC60to30v3wLI.GMPAS-DIB-IAF-ISMF.cori-haswell_gnu -q debug --walltime 00:30:00
```
Tested with both gnu and intel. Run completes but comparison fails, as before, and for both the default ` config_gm_closure = 'EdenGreatbatch'` and ` config_gm_closure = 'constant'`. @stephenprice and @darincomeau I mentioned on the call today I thought it would pass with constant GM, but I was wrong. I'm working further on this now.

**Comment by stephenprice** [comment]
Thanks for the update @mark-petersen.

**Comment by mark-petersen** [comment]
Well, if I was paid by the character, this would certainly be the highest-priced one so far. This was the fix:
```
src/core_ocean/shared/mpas_ocn_tracer_hmix_redi.F
@@ -189,7 +189,7 @@ contains
-      nCells = nCellsArray(1)
+      nCells = nCellsArray(2)
```
It took a long time because the test only failed after PR #3825, but this code is not even in that PR. I kept testing alternate before/after versions of that PR to whittle down the possibilities, but it turns out that the error was there in both cases. But before PR #3825 when GM was on, the GM part altered some of the Redi variables, so actually corrected the previous error. When the Redi variables were cleanly separated from the GM section in #3825 (which they should be), it revealed this problem. But the extra halo computation is only needed with melt fluxes on, making it even more obscure.  Thanks for your patience.
