### ISSUE TITLE
LCHUNKS error with ne11 F-case using DEBUG and threads on Anvil

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#3961]
On Anvil, with DEBUG, we see the following error with `res=ne11_ne11 compset=FC5AV1C-L`

```
 24: forrtl: severe (408): fort: (2): Subscript #1 of the array LCHUNKS has value 827 which is greater than the upper bound of 826
 24:
 24: Image              PC                Routine            Line        Source
 24: e3sm.exe           000000000CFDF250  Unknown               Unknown  Unknown
 24: e3sm.exe           00000000039397D5  phys_grid_mp_phys        1015  phys_grid.F90
 24: e3sm.exe           000000000426ABC5  inital_mp_cam_ini          40  inital.F90
 24: e3sm.exe           000000000087D34F  cam_comp_mp_cam_i         155  cam_comp.F90
 24: e3sm.exe           0000000000838445  atm_comp_mct_mp_a         315  atm_comp_mct.F90
 24: e3sm.exe           00000000004652ED  component_mod_mp_         257  component_mod.F90
 24: e3sm.exe           0000000000429C61  cime_comp_mod_mp_        1399  cime_comp_mod.F90
 24: e3sm.exe           000000000045BDE1  MAIN__                    122  cime_driver.F90
 24: e3sm.exe           0000000000416E1E  Unknown               Unknown  Unknown
```

I see the error with intel18 compiler and with 8 nodes using threads (144 MPI's with 18x2).

Same test on Cori does not fail in this way (but does require a fix as explained here https://github.com/E3SM-Project/E3SM/issues/3628 to run in DEBUG -- we don't think that issue is otherwise related to this one)

@worleyph found that changing -O0 to -O1 in the DEBUG definition in Macros.cmake eliminates the error

**Comment by worleyph** [comment]
See https://github.com/E3SM-Project/E3SM/issues/3628#issuecomment-730714306 for further information.

**Comment by worleyph** [comment]
and https://github.com/E3SM-Project/E3SM/issues/3628#issuecomment-731499201 .

**Comment by ndkeen** [comment]
I see the intel19 compiler is a module on Anvil, but I was unable to easily try this as it apparently needs other module changes.

**Comment by ambrad** [comment]
One interesting thing as I look through some routines: proc_heap_adjust has some variables that ought to be integers but are instead real(r8). I'll document these here.

Decls:
```f90
   integer, intent(inout)  :: heap(heap_dlen)
   real(r8):: proc_ip      ! process id of parent of current element
   real(r8):: proc_il      ! process id of left child of current element
   real(r8):: proc_ir      ! process id of right child of current
                           !  element
```
Uses:
```f90
         proc_ip = heap(heap_ip) ! double <- int
         heap(heap_i)      = proc_ip  ! int <- double
         inv_heap(proc_ip) = heap_i ! indexing with a double
         ! same pattern for proc_il; omitted
         ! same pattern for proc_ir; omitted
```

**Comment by worleyph** [comment]
Bummer. Thought that @amametjanov had already found all of these "cut and paste" errors for me (was embarrassing enough the first time). I'll check this out.

**Comment by ambrad** [comment]
Oh, yes, I see it's in this PR: https://github.com/E3SM-Project/E3SM/pull/3855. In principle int <- double <- int should cause no problems (I can't find the IEEE floating point rule that supports this, but it seems reasonable to expect int32-double conversions to retain the integer value since the double's mantissa has plenty of bits to retain the int32's full information content), but it might be worth fixing them in the failing Anvil case. Maybe something in the compiler in that instance is causing the conversions to be incorrect. (Unlikely.)

**Comment by worleyph** [comment]
Worth checking though - easy enough to do.

**Comment by worleyph** [comment]
Fixing the declaration errors did not eliminate the LCHUNK array indexing error.

**Comment by worleyph** [comment]
Found the source of the problem I identified previously, but fixing this does not eliminate the failure. I'll summarize the identified bug/fix soon, but want to spend my time on restarting tracking the failure.

**Comment by worleyph** [comment]
Correction: this bug fix did eliminate the failure.

Problem is in the call to 

                 call proc_heap_adjust(inv_proc_heap(ntmp2), proc_heap_remove,   &
                                       max_nvsmptasks, proc_heap_len, proc_heap, &
                                       proc_cost, inv_proc_heap)

in phys_grid.F90 where

        subroutine proc_heap_adjust(updated, remove, heap_dlen, &
                                    heap_len, heap, cost, inv_heap)
     ...
        integer, intent(in)     :: updated
     ...
        integer, intent(inout)  :: inv_heap(0:npes-1)

'inv_heap' is modified in the routine proc_heap_adjust, and changes the value at the location 'inv_proc_heap(ntmp2)'. Compilation with optimization greater than -O0 apparently caches this value (since it is declared 'intent(in)'), so 'updated' is not changed within the scope of the 'proc_heap_adjust' routine. -O0 compilation does not, changing the value on 'updated' internally when 'inv_proc_heap(ntmp2)' is changed. Simplest (only?) solution is to

                 integer :: updated
                 ...
                 updated = inv_proc_heap(ntmp2)
                 call proc_heap_adjust(updated, proc_heap_remove,   &
                                       max_nvsmptasks, proc_heap_len, proc_heap, &
                                       proc_cost, inv_proc_heap)

**Comment by ambrad** [comment]
> Simplest (only?) solution

Very subtle error. As a matter of curiosity, I wonder what would happen if you instead just add the `value` annotation to the `updated` parameter:
```f90
    integer, value, intent(in)     :: updated
```

**Comment by worleyph** [comment]
@ambrad, thanks. Was thinking that this would not have happened with C or C++ code, as would have used call-by-value as a matter of course. Depite being around since 2003, I was not aware of the 'value' attribute. Seems like this is what you would want for any scalar argument (instead of intent(in) - intent(in) doesn't add anything if you specify 'value', does it?)

The subroutine does not "know" that aliased variables are being passed in, so seems more like a style issue, to use it everywhere ...

What is your preference? I'll add a comment in either case, either saying copying to scalar to prevent aliasing or not copying to scalar but adding a comment that declaring variable as 'value' in order to prevent aliasing.

**Comment by ambrad** [comment]
In my own F90 code I generally do not use `value`, as the annotation seems counter to standard style. The exception is C++-F90 bridges, which often require it. I was just curious if it fixes this particular problem.

Have you tried compiling with gnu? I'm wondering if gfortran's `-Waliasing` catches this error. Might be worth checking if there are other places in E3SM that has inadvertent aliasing.

**Comment by worleyph** [comment]
@ndkeen runs with gnu I believe (not always successfully :-) ). Perhaps Noel has some insight here.

**Comment by ndkeen** [comment]
I finally got to this, added the aliasing warning flag, rebuilding, and then realized that we already have `-Wall` for gnu debug builds which has that included.  Doh. And I'm not seeing any warnings about aliasing. 

However, there are a lot of warnings. Some might be worth investigating?

```
       -Wall
           Enables commonly used warning options pertaining to usage that we recommend avoiding and that we believe are
           easy to avoid.  This currently includes -Waliasing, -Wampersand, -Wconversion, -Wsurprising, -Wc-binding-type,
           -Wintrinsics-std, -Wtabs, -Wintrinsic-shadow, -Wline-truncation, -Wtarget-lifetime, -Winteger-division,
           -Wreal-q-constant, -Wunused and -Wundefined-do-loop.
```

Is it true that PR 3963 will address this issue?

**Comment by worleyph** [comment]
> Is it true that PR 3963 will address this issue?

This is what it is for. It did eliminate the problem with the reproducer.
