### ISSUE TITLE
Segfault with several PE layouts using RRM v2 config on chrysalis

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4198]
Using master as of earlier today (Apr 1), I tried using the latest run_e3sm script from @tangq with some modifications of my own to change PE layout.  Several of my attempts fail with the error below.

I tried DEBUG and it doesn't fail (for one layout that was failing).  

```
453: [chr-0444:463739:0:463739] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x21)
453: ==== backtrace (tid: 463739) ====
453:  0 0x0000000000055969 ucs_debug_print_backtrace()  ???:0
453:  1 0x0000000000012b20 .annobin_sigaction.c()  sigaction.c:0
453:  2 0x0000000001bed339 bndry_mod_base_mp_sort_neighbor_buffer_mapping_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/homme/src/share/bndry_mod_base.F90:1011
453:  3 0x0000000001c80d84 prim_driver_base_mp_prim_init1_elem_arrays_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/homme/src/share/prim_driver_base.F90:635
453:  4 0x0000000001c83489 prim_driver_base_mp_prim_init1_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/homme/src/share/prim_driver_base.F90:125
453:  5 0x00000000021fb689 dyn_comp_mp_dyn_init1_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/dynamics/se/dyn_comp.F90:149
453:  6 0x0000000001bd0dd7 inital_mp_cam_initial_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/dynamics/se/inital.F90:36
453:  7 0x0000000000506ccf cam_comp_mp_cam_init_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/control/cam_comp.F90:155
453:  8 0x00000000004ff39d atm_comp_mct_mp_atm_init_mct_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/components/eam/src/cpl/atm_comp_mct.F90:315
453:  9 0x0000000000441494 component_mod_mp_component_init_cc_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/cime/src/drivers/mct/main/component_mod.F90:257
453: 10 0x000000000042fdee cime_comp_mod_mp_cime_init_()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/cime/src/drivers/mct/main/cime_comp_mod.F90:1415
453: 11 0x000000000043e37a MAIN__()  /lcrc/group/e3sm/ac.ndkeen/wacmy/rrmv2-bigrid/20210401/cime/src/drivers/mct/main/cime_driver.F90:122
453: 12 0x000000000041d622 main()  ???:0

/lcrc/group/e3sm/ac.ndkeen/E3SM_simulations/v2beta3.cmmod023a32x2.5d.wh0.wr
```

Layouts I've tried just to indicate no real pattern, though I haven't seen a fail without threads yet.

```
20 nodes 32x2 OK
23 nodes 32x2 fail
23 nodes 32x2 DEBUG (ran for 2 days until running out of time)
29 nodes 64x1 OK
30 nodes 32x2 fail
32 nodes 32x2 fail
39 nodes 32x2 fail
50 nodes 64x1 OK
50 nodes 32x2 fail
50 nodes 16x4 fail
```

**Comment by ambrad** [comment]
@ndkeen would you mind replacing the calls to
```
  use edge_mod, only : ghostvpack_unoriented, ghostvunpack_unoriented
```
with
```
  use sl_advection, only: amb_ghostvpack_unoriented, amb_ghostvunpack_unoriented
```
and seeing what happens? You'll need to go into sl_advection.F90 and add those two routines to the public list at line 39 of sl_advection.F90. Thanks.

**Comment by tangq** [comment]
@ndkeen , do you see this issue with the code I am using (hash: dbdd4b32c4b77686cb816ab2fedca3011a46638c)? It is the master on March 5.

**Comment by ambrad** [comment]
@ndkeen never mind about the above. I've assigned myself to this issue.

**Comment by rljacob** [comment]
What is the case?  We should add it to our test suite.

**Comment by ambrad** [comment]
It's the RRMv2 case. I suspect Chrysalis is revealing a bug in some old initialization code that only SL transport initialization calls. Noel, correct me if I'm wrong, but I think we ran a large number of PE layouts on Compy and Cori-KNL without hitting this.

**Comment by singhbalwinder** [comment]
I recently worked on a case which was passing in DEBUG but failing otherwise. The reason behind that was the use of `where` function to an array which had NaNs in the production style run and zeros in the debug mode. I replaced `where` with an explicit `if` condition and it worked fine.

Another reason could be running out of memory in non-debug cases. That doesn't seem to be the case here but it doesn't hurt trying to request less than max number of procs per node. That would mean that we are changing the PE layout which may defeat the purpose of getting the code running with the current (non-working) PE-layout.

**Comment by ndkeen** [comment]
Andrew: OK, will continue communicating on slack.

Qi: Thanks, good suggestion. I just tried using the hash you suggested with a previously failing 32-node 32x2 case and it worked. Which I suppose means there must be something in code between March 5 and Apr 1?

Rob:
Using a run_e3sm script, but the basic setup is:
COMPSET="WCYCL1850"
RESOLUTION="northamericax4v1pg2_WC14to60E2r3"
Have not tried something simpler yet.

**Comment by ndkeen** [comment]
Here is an 18-node case that fails in the same way.

`/gpfs/fs1/home/ac.ndkeen/my-run.20210401.v2beta3.rrm.cmod018as32x2.5d.wh0.wr.csh`

I am running tests now, but I think using 64x1 will work as well as 32 MPI's per node and 2 threads in all components except ATM -- ie I think it's just threading in ATM.

**Comment by tangq** [comment]
@ndkeen , I agree that your tests suggest that the code changes between March 5 and April 1 are likely the cause.

**Comment by ndkeen** [comment]
The out-of-the-box test for this compset needs `xmlchange ATM_NCPL=48` and will work.
For example `create_test SMS_P576x2.northamericax4v1pg2_WC14to60E2r3.WCYCL1850 --walltime=00:30:00`
I've only tried a few layouts, but I've not been able to reproduce the fail.
The differences in settings in run_e3sm script are minor and I wouldn't think they would have impact.

**Comment by rljacob** [comment]
Our prod test suite has northamericax4v1pg2_WC14to60E2r3.A_WCYCL1850S_CMIP6.  Should we change that?

**Comment by ambrad** [comment]
I isolated the issue.

Observations:
* doesn't fail: no `-cosp`
* doesn't fail: `<append DEBUG="FALSE">-O2 -traceback -check bounds -check pointers -qno-opt-dynamic-align</append>`
* doesn't fail: `<append DEBUG="FALSE">-O2 -traceback -check bounds -qno-opt-dynamic-align</append>`
* fails: `<append DEBUG="FALSE">-O2 -traceback -qno-opt-dynamic-align</append>`
* doesn't fail: in `GhostVunpack_unoriented`, declare and use `v` as `v(:,:,:,:)` instead of `v(nc,nc,vlyr,*)`

I don't see an indication that `v(nc,nc,vlyr,*)` is a bug, but I also don't use assumed-shape arrays, so I might be missing a subtlety.

I believe the fact that this code fails now but not in an older git ref is a red herring; either the assumed-shape array _is_ a long-latent bug that is rarely triggered, or caprices of -O2 compilation on a new-ish architecture are causing failures now.

This Homme init code is very old and needed a serious cleanup, so I'm doing that while addressing this issue, too. Of greatest importance is `sort_neighbor_buffer_mapping` was needlessly making two O(nelemd)-sized arrays.

I'll issue a PR for [this branch](https://github.com/ambrad/E3SM/tree/ambrad/homme/issue-4198) once I've done some integration testing.

**Comment by ambrad** [comment]
@ndkeen are you interested in trying that branch out with your script that iterates over PEs?

@oksanaguba may I make you the integrator when the PR is ready?

**Comment by ndkeen** [comment]
OK, so you did see that it only happens with COSP -- interesting.
Sure, I can try out a PR.

**Comment by oksanaguba** [comment]
@ambrad  yes.

**Comment by ambrad** [comment]
Noel reports that the 18-node reproducer indeed now works for him, but other cases still fail. So we'll investigate further with other reproducers.

**Comment by ambrad** [comment]
Adding `!DIR$ NOOPTIMIZE` to sort_neighbor_buffer_mapping, like this:
```F90
#if defined _OPENMP && defined __INTEL_COMPILER
  ! On Chrysalis in threaded builds, this routine sometimes fails. To be                                                                                                                      
  ! clear, this routine is not called in a threaded region, but compiling with                                                                                                                
  ! -qopenmp with optimization somehow emits code that perhaps has a bug. See                                                                                                                 
  ! https://github.com/E3SM-Project/E3SM/issues/4198                                                                                                                                          
  !DIR$ NOOPTIMIZE                                                                                                                                                                            
#endif
```
makes all the PE layouts I now have run. This isn't the first time I've needed to use this directive; see, e.g., https://github.com/E3SM-Project/E3SM/blob/6db49a63ae03623911799f860ffc76c8538bdf20/components/homme/src/share/gllfvremap_mod.F90#L343-L353

**Comment by ambrad** [comment]
Noel and I have tried several other things:
* FORCE_BUILD_SMP=TRUE but with 1 thread fails without the NOOPTIMIZE workaround. This makes sense: the code that segfaults isn't threaded, so it must be something affected by the code emitted by the compiler, and this code in general can be affected by -qopenmp.
* 5 different cases without cosp (including a 4x16 case) all complete 5 days without the workaround.
* If we remove PR #4136, remove the workaround, and use -cosp, we don't get the failure. That doesn't mean 4136 is the problem, but it apparently was the perturbation to the code base that revealed the issue.
* The NOOPTIMIZE workaround seems to work for all PE layouts.

Possibilities:
* Perhaps there's an issue in COSP after the CAMRT removal...
* ...or just revealed by it.
* Or there could be a problem in the code emitted for sort_neighbor_buffer_mapping, and somehow COSP initialization triggers the problem.

Status: We have a workaround for the symptom but haven't IDed the root cause.

**Comment by ndkeen** [comment]
Also, I tried `SMS_P576x2.northamericax4v1pg2_WC14to60E2r3.WCYCL1850.chrysalis_intel.eam-cosplite` (which again requires ATM_NCPL=48 to work) and it doesn't fail. I can create a simpler set of commands that will demonstrate error if that helps (as opposed to running run_e3sm script).

**Comment by ndkeen** [comment]
I just needed cosp. Not sure the difference between cosplite and cosp, but might be good to have some tests with cosp. This script should reproduce error:

```
#!/bin/csh                                                                                                                                                    

set workspace=/lcrc/group/e3sm/ac.ndkeen/E3SM_simulations
set casename=$workspace/v2beta3.n030.32x0

create_newcase --case $casename --output-root $workspace --compset WCYCL1850 --res northamericax4v1pg2_WC14to60E2r3 --machine chrysalis --project e3sm --wall\
time 0:40:00
cd $casename

./xmlchange --id CAM_CONFIG_OPTS --append --val='-cosp'
./xmlchange ATM_NCPL="48"

./xmlchange STOP_OPTION="ndays"
./xmlchange STOP_N="1"
./xmlchange REST_OPTION="none"

./xmlchange MAX_MPITASKS_PER_NODE="32"
./xmlchange MAX_TASKS_PER_NODE="128"

./xmlchange NTASKS_ATM="960"
./xmlchange ROOTPE_ATM="0"

./xmlchange NTASKS_LND="960"
./xmlchange ROOTPE_LND="0"

./xmlchange NTASKS_ICE="960"
./xmlchange ROOTPE_ICE="0"

./xmlchange NTASKS_OCN="960"
./xmlchange ROOTPE_OCN="0"

./xmlchange NTASKS_CPL="960"
./xmlchange ROOTPE_CPL="0"

./xmlchange NTASKS_ROF="960"
./xmlchange ROOTPE_ROF="0"

./xmlchange FORCE_BUILD_SMP="TRUE"
./xmlchange NTHRDS_ATM="1"
./xmlchange NTHRDS_LND="1"
./xmlchange NTHRDS_ICE="1"
./xmlchange NTHRDS_OCN="1"
./xmlchange NTHRDS_CPL="1"
./xmlchange NTHRDS_GLC="1"
./xmlchange NTHRDS_ROF="1"
./xmlchange NTHRDS_WAV="1"

./xmlchange GMAKE_J="16"

./case.setup

./case.build

./case.submit
```

This forces build to use openmp flag, but then only actually uses 1 thread.
Can change that to use 2 threads and still see same issue.

**Comment by ambrad** [comment]
@ndkeen are you saying that, leaving out the NOOPTIMIZE workaround, cosplite _does not_ cause a seg fault, but cosp does?

**Comment by ambrad** [comment]
One data point for Compy: This threaded config run with master _does not_ fail:
```
    ./xmlchange MAX_MPITASKS_PER_NODE="40"
    ./xmlchange MAX_TASKS_PER_NODE="40"
    ./xmlchange NTASKS_ATM="600"
    ./xmlchange ROOTPE_ATM="0"
    ./xmlchange NTASKS_LND="600"
    ./xmlchange ROOTPE_LND="0"
    ./xmlchange NTASKS_ICE="600"
    ./xmlchange ROOTPE_ICE="0"
    ./xmlchange NTASKS_OCN="600"
    ./xmlchange ROOTPE_OCN="0"
    ./xmlchange NTASKS_CPL="600"
    ./xmlchange ROOTPE_CPL="0"
    ./xmlchange NTASKS_GLC="16"
    ./xmlchange ROOTPE_GLC="0"
    ./xmlchange NTASKS_ROF="600"
    ./xmlchange ROOTPE_ROF="0"
    ./xmlchange NTASKS_WAV="16"
    ./xmlchange ROOTPE_WAV="0"
    ./xmlchange NTHRDS_ATM="2"
    ./xmlchange NTHRDS_LND="2"
    ./xmlchange NTHRDS_ICE="2"
    ./xmlchange NTHRDS_OCN="2"
    ./xmlchange NTHRDS_CPL="1"
    ./xmlchange NTHRDS_GLC="1"
    ./xmlchange NTHRDS_ROF="2"
    ./xmlchange NTHRDS_WAV="1"
```

**Comment by ndkeen** [comment]
Good point. It fails with `./xmlchange --id CAM_CONFIG_OPTS --append --val='-cosp'` but I'm not sure the exact command to get "cosp_lite", I just know the `create_test` invocation with "cosp_lite" did work. 

I also tried on Cori with the simple script above and it ran without a fail.

**Comment by ambrad** [comment]
We have already observed that we don't see the problem with DEBUG=true, as well as -O2 but with some -check flags. So valgrind is the next thing to try. Chrysalis doesn't seem to have valgrind; thus, even though the issue doesn't seem to occur on Compy, I still ran it there with valgrind. I didn't find anything.

**Comment by xylar** [comment]
Please forgive the noob question but would this issue explain why @cbegeman and I are having trouble creating a baseline for the following test?
```
SMS_PS.northamericax4v1pg2_WC14to60E2r3.A_WCYCL1850S_CMIP6.chrysalis_intel.allactive-wcprodrrm
```
I'm not sure if this is one of the affected layouts or not.

**Comment by ambrad** [comment]
@xylar, would you point me to a directory where it has failed? My impression is that test isn't affected because it doesn't have COSP on, but I might be wrong.

**Comment by xylar** [comment]
@ambrad, I'm happy to open a new issue if this turns out to be unrelated, but I'm not very qualified to even state the problem.  The output directory for the most recent attempt is here:
```
/lcrc/group/e3sm/ac.xylar/scratch/chrys/SMS_PS.northamericax4v1pg2_WC14to60E2r3.A_WCYCL1850S_CMIP6.chrysalis_intel.allactive-wcprodrrm.G.20210406_050025_aeqni5
```

**Comment by ambrad** [comment]
@xylar, I was confusing this with Noel's above test. The case you're running does have -cosp in the build configuration, and the e3sm.log output indeed shows the run failure reported in this issue.

**Comment by xylar** [comment]
Great, I'm glad I didn't find something new.  And thanks for working on it!

**Comment by brhillman** [comment]
FYI, I believe cosplite disables the radar simulator, so if cosp fails but cosplite does not, perhaps that points to the radar simulator code.

**Comment by ambrad** [comment]
@xylar the workaround is now in master. Let me know if you still have the issue you reported above.

**Comment by xylar** [comment]
Thanks @ambrad!  I'll be redoing that testing in the next few days and will let you know if I have any trouble.

**Comment by ndkeen** [comment]
Noting that using a master of Apr12th that includes this fix, I've run over 100 different PE layout on chrysalis and have not encountered this error. That includes at least one DEBUG run. I have only tested with Intel and only on chrysalis.

**Comment by worleyph** [comment]
> Good point. It fails with ./xmlchange --id CAM_CONFIG_OPTS --append --val='-cosp' but I'm not sure the exact command to get "cosp_lite", I just know the create_test invocation with "cosp_lite" did work.

Note that adding '-cosp' by default sets 

     &cospsimulator_nl
      cosp_lite              = .true.
      docosp         = .true.
     /

As far as I can tell, the only difference between 

     SMS_P576x2.northamericax4v1pg2_WC14to60E2r3.WCYCL1850.chrysalis_intel.eam-cosplite

and 

     --compset WCYCL1850 --res northamericax4v1pg2_WC14to60E2r3

with Noel's "reproducer" PE layout is the layout. That is the SMS test uses 576x1 stacke PE layout while Noel's reproducer uses 960x1 . Noel - please correct if you also changed the PE layout in your SMS_P576x2.northamericax4v1pg2_WC14to60E2r3.WCYCL1850.chrysalis_intel.eam-cosplite experiments.

**Comment by worleyph** [comment]
I haven't been able to find out anything new about this issue. One of the many things that puzzles me is that I can't replicate the error using an F or WCYCL1850 case using a non-RRM mesh. I've done diffs on the case directories and, based on this, modified the code in prim_driver_base.F90 to force 

     can_scalably_init_grid = .false.

but this was not sufficient to reproduce the failure. I also compared the atm_in for the two WCYCL1850 cases, and the only differences I saw that I could adapt to in user_nl_eam were

     hypervis_scaling = 3.0 
     hypervis_subcycle = 2 
     hypervis_subcycle_tom = 3
     se_tstep = 75

which caused the non-RRM case to fail with 

      ERROR: EOS bad state: d(phi), dp3d or vtheta_dp < 0

This failure occurs much later in the run than that in the RRM case, and also occurs with or without @ambrad 's fix, so is probably unrelated. (I am interested in understanding why the non-RRM case can't run with these settings though. This was with a resolution or ne30pg2_oECv3.)

Noel's experiments are reassuring, but the object files for the RRM and non-RRM cases are all the same size except for the buffer.mod and physics_buffer.mod (both of which are source-to-source translated before being compiled, so probably have the case names imbedded in them), so I am surprised that a compiler error would affect one case but not the other when the code generation appears to be identical.

Having no new ideas to try at the moment, I'll let this be for now.

**Comment by mt5555** [comment]
one key difference:  RRM meshes and all non-NE30 meshes use "tensor hyperviscosity", while NE30 uses the older constant coefficient hyperviscosity due to wanting to preserve BFB during V2 watercycle tuning.  
But tensor HV requires a different viscosity coefficieint.   The RRM requires tensorHV, but the NE30 mesh can use either.  To make the ne30 use the same formulation as RRM, you need:

hypervis_scaling = 3.0    ! turn on tensor HV
nu=3.4e-8          ! one coefficient works for all resolutions

The tensorHV does use a slightly different code path, in the laplace operator

**Comment by worleyph** [comment]
@mt5555 , thanks. I also tried the resulotion ne120pg2_r05_oECv3 (without reproducing the error), but will follow your suggestions for ne30pg2, just for completeness and to verify.

**Comment by ndkeen** [comment]
Regarding my suggestion that it fails with cosp, but not with cosp_lite, that was premature. I think what I reported is true, (the `SMS_P576x2` layout might just work either way), but a more fair comparison is to take the above 30 node launch script and edit:

```
cat <<EOF user_nl_eam 
cosp_lite=.true.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
docosp=.true.                                                                                                                                                                                                                                                                   
EOF                                                                                                                                                                                                                                                                             
```

ie, with COSP enabled, try with/without cosp_lite and I see the same segfault either way. (Works without COSP at all). So I now believe it's an issue with cosp enabled (regardless of cosp_lite).

**Comment by worleyph** [comment]
I took @ndkeen 's latest reproducer (with -cosp, with FORCE_BUILD_SMP "true", using 960x1 stacked PE layout with  MAX_MPITASKS_PER_NODE=32 and MAX_TASKS_PER_NODE=128) and modified it to get it to run on 4 nodes:

     - MAX_MPITASKS_PER_NODE=64 and MAX_TASKS_PER_NODE=128
     - ATM NTASK <=  64, ATM ROOTPE = 0
     - LND NTASK  =  64, LND ROOTPE = 0
     - ROF NTASK  =  64, ROF ROOTPE = 0
     - ICE NTASK  = 144, ICE ROOTPE = 64
     - OCN NTASK  = 160, OCN ROOTPE = 64
     - CPL NTASK  = 192, CPL ROOTPE = 64

So ATM, LND, ROF stacked on one node, and ICE, OCN, CPL stacked on 3 nodes. Ran into what appeared to be memory issue failures when all components were stacked on the same nodes with these  PE counts.

Running without @ambrad 's fix, I then varied ATM NTASK, with the following results:

     64: failed in usual place in bndry_mod_base.F90
     60: failed in usual place in bndry_mod_base.F90
     48: failed in usual place in bndry_mod_base.F90
     32: failed in usual place in bndry_mod_base.F90
     30: failed in usual place in bndry_mod_base.F90
     24: failed in usual place in bndry_mod_base.F90
     22: failed in usual place in bndry_mod_base.F90
     21: worked
     20: worked
     19: worked
     18: worked
     17: failed in usual place in bndry_mod_base.F90
     16: worked once, failed in usual place in bndry_mod_base.F90 twice

To the extent I investigated, these results were reproducible, with the exception of ATM NTASK=16, where I got one success along with the two failures.

I then repeated some of the experiments but with 

     - MAX_MPITASKS_PER_NODE=32 and MAX_TASKS_PER_NODE=128
     - ATM NTASK <=  32, ATM ROOTPE = 0
     - LND NTASK  =  32, LND ROOTPE = 0
     - ROF NTASK  =  32, ROF ROOTPE = 0
     - ICE NTASK  = 144, ICE ROOTPE = 32
     - OCN NTASK  = 160, OCN ROOTPE = 32
     - CPL NTASK  = 160, CPL ROOTPE = 32

This uses 6 nodes, and was to allow "space" for increasing the number of threads to 2 without using hyperthreading. Still using one thread:

     32: worked once, failed in usual place in bndry_mod_base.F90 once
     30: failed in usual place in bndry_mod_base.F90
     24: failed in usual place in bndry_mod_base.F90
     22: failed in usual place in bndry_mod_base.F90
     21: failed in usual place in bndry_mod_base.F90
     20: worked (twice)
     19: failed in usual place in bndry_mod_base.F90
     18: worked twice, failed in usual place in bndry_mod_base.F90 once
     17: failed in usual place in bndry_mod_base.F90
     16: worked twice

Seems like results varied more from run to run? Somewhat more frequent error instances?

Finally, I tried some experiments with 2 threads per proces (ATM only), using otherwise the same 6 node PE layout.

     32x2: worked (twice)
     30x2: worked
     24x2: worked
     20x2: worked
     18x2: died in a new location in sl_advection.F90 (twice) (see below)
     16x2: died in sl_advection.F90

So none of these failed in bndry_mod_base.F90 even without @ambrad's fix, but a new failure occurred.

Repeated some of the 2 thread runs with @ambrad's fix, and the new failures were unaffected:

     18x2: died in sl_advection.F90
     16x2: died in sl_advection.F90

New failure was also a seg. fault, e.g.

       9: forrtl: severe (174): SIGSEGV, segmentation fault occurred
       9: e3sm.exe           0000000001CA1A54  sl_advection_mp_a         645  sl_advection.F90
       9: e3sm.exe           0000000001CA4930  sl_advection_mp_p         216  sl_advection.F90
       9: e3sm.exe           0000000001C7F978  prim_driver_base_        1413  prim_driver_base.F90
       9: e3sm.exe           0000000001C7E59B  prim_driver_base_        1170  prim_driver_base.F90
       9: e3sm.exe           00000000021FC577  dyn_comp_mp_dyn_r         364  dyn_comp.F90

The loop in question (line 645) is threaded. 

Not sure what to do with this yet. Just a FYI so far. The failure in sl_advection occurs only for smaller process counts (so far), so perhaps a memory issue? I'll try to verify this.

**Comment by ambrad** [comment]
@worleyph the unrelated error might be due to memory usage. If you're curious, you might try replacing the Qtens stack array used in line sl_advection.F90:645 with an allocatable one to see if that fixes it.

**Comment by worleyph** [comment]
@ambrad, the failure in sl_advection was eliminated for the 16x2 ATM case by increasing OMP_STACKSIZE from 128M (the current default) to 256M (so was due to memory usage).

**Comment by worleyph** [comment]
Looking at the original error, the segfault being reported from within the libpthreads library still seems strange:

     33: libpnetcdf.so.3.0  0000155550C65789  for__signal_handl     Unknown  Unknown
     33: libpthread-2.28.s  000015554D623B20  Unknown               Unknown  Unknown
     33: e3sm.exe           0000000001BEF9AF  bndry_mod_base_mp        1014  bndry_mod_base.F90

though perhaps this is a given for any code built with threading support? I did add 

     if (par%masterproc) write(iulog,*) 'omp_get_level==...', omp_get_level() 

and this verified that sort_neighbor_buffer_mapping is being called from a sequential region. Note that the addition of the print statement also made the failure disappear. I also made the error "disappear" by adding a critical section around the loop where the failure is occurring:

     !$omp critical
       do ie=nets,nete
     ...
          call ghostVpack_unoriented(ghostbuf_cv, cin,nc,nlev,kptr,elem(ie)%desc)
       enddo
     !$omp end critical 

Since the hypothesis is that this is a compiler bug that is eliminated by lowering optimization, code changes in the same location that eliminate the problem do not disprove the hypothesis.

However, I did remove my changes to sort_neighbor_buffer_mapping, but added a critical section around the body of the routine ghostVpack_unoriented in edge_mod_base.F90, and this also eliminated the problem. Perhaps the opimization is inlining the call to ghostVpack_unoriented, and something is going wrong when built with threading support? Still seems strange that the error is sensitive to PE layout (problem decomposition) and is not completely deterministic (nor completely random) and also have only observed it with the RRM mesh case.

**Comment by worleyph** [comment]
Adding a noinline directive before the call to ghostVpack_unoriented:

     !DIR$ NOINLINE                                                                                                                                                                                                                  
          call ghostVpack_unoriented(ghostbuf_cv, cin,nc,nlev,kptr,elem(ie)%desc)

did not eliminate the error. However, adding

     !DIR$ NOOPTIMIZE          

to subroutine GhostVpack_unoriented did eliminate the failure. Note that adding a critical section inside this routine eliminated the failure for one PE layout, but not for all. Similarly, adding a critical section around the loop in sort_neighbor_buffer_mapping  did not eliminate the failure in all PE layouts (so previous comments to these effects were in error).

@ambrad's fix is probably less intrusive than adding NOOPTIMIZE to GhostVpack_unoriented, being applied to a routine that is called only during initialization.
