### ISSUE TITLE
remove landm_coslat array

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#4276]
during modernization of the topo data set tool chain, I was looking at the landm_coslat() array.  

This array is in all our EAM topo input files, but isn't currently used.

documented places where it appears in the code:

It is read during initialization (in phys_inidat()
It is stored as a global array in the comsrf module
It is passed as an argument in tphysbc()

It is used in stratiform_tend(), called when the 'RK' microphysics scheme is turned on (not used in E3SM)
(actually use in in cldwat.F90::pcond() called by stratiform)_tend)

It appears in the RRTMG interface.  RRTMG will write it to history files, but otherwise doesn't appear to use it.  RRTMGP doesn't use it at all.

restart_physics.F90: written to restart file

Suggestion: Lets remove this array, so we dont have to compute it in the topo tool chain, dont have to read it during init, and dont have to read/write it to restart files.

**Comment by mt5555** [comment]
ran a few F compset tests with landm_coslat=0 instead of reading from a file. they were all BFB with baselines.

**Comment by brhillman** [comment]
LANDM is actually still being used in MMF for effective radius calculations (we use the old CAM effective radius routines because we do not have a meaningful effective radius assumption from the sam1mom microphysics). I do not understand yet what the difference is between LANDFRAC and LANDM, but I think we can probably drop LANDM in favor of just LANDFRAC. The main difference, I assume, is that LANDM comes from the atmosphere topo, but LANDFRAC probably comes from the land surface models input data or masks (landfrac is a member of cam_in, which is fields that are passed from the other component models to the atmosphere).

**Comment by brhillman** [comment]
Here is the difference between LANDM and LANDFRAC at ne4pg2: 
![image](https://user-images.githubusercontent.com/15826727/124677542-8ba02400-de75-11eb-9296-48a54e66c352.png)
