### ISSUE TITLE
E3SMv2 production code has zero land dry deposition with 'xactive_lnd'

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/E3SM#4470]
I reproduced this error with the E3SMv2 historical run by only changing the dry deposition method to ‘xactive_lnd’. The case is located at chrysalis: /lcrc/group/e3sm/ac.qtang/E3SM_simulations/v2.LR.drydep_atm_historical_0101/tests/S_1x10_ndays/run.
 
This error does NOT affect the ongoing E3SMv2 DECK runs, because they use the ‘xactive_atm’ method.

This error will affect all the atmosphere NGD runs with chemistry and the BGC tests coupling with chemistry.

**Comment by peterdschwartz** [comment]
@tangq I am testing a fix that may be due to creating an elm specific version of seq_drydep_mod.F90 to use for an OpenACC implementation.  I have been able to copy and run your case on chrysalis.  Changing back to the shared seq_drydep_mod.F90, I compared the history variables:
`['DF_DMS','DF_H2O2','DF_H2SO4','DF_O3','DF_SO2','DF_SOAG']`
with those in `/lcrc/group/e3sm/ac.qtang/E3SM_simulations/v2.LR.drydep_atm_historical_0101/tests/S_1x10_ndays/run/v2.LR.drydep_atm_historical_0101.eam.h0.2000-01-02-00000.nc`

This caused a lot of differences in the values in addition to making the values that were zero be non-zero. 
I saw you reference a PowerPoint in the email but it didn't come with the email that was forwarded to me, so I can't say if it's fixed.  Here is my branch https://github.com/E3SM-Project/E3SM/tree/peterdschwartz/lnd/DDLND_fix  If you want to merge it your own and test if the values are reasonable.

**Comment by tangq** [comment]
@peterdschwartz , I emailed you the slides I sent in my email.

Can you point me to your simulation with the shared seq_drydep_mod.F90? I'd like to see how it compares to my results.

Are you expecting that the shared seq_drydep_mod.F90 (your run) and the elm seq_drydep_mod.F90 (my run) produce the same DF_* over the ocean? But that's not the case?

I will test your fix with my previous chemistry simulations to see if the dry deposition fluxes are reasonable or not.

**Comment by peterdschwartz** [comment]
@tangq my run directory is here `/lcrc/group/e3sm/ac.schwartzpd/drydep/output/v2.LR.drydep_atm_historical_0101/run`

I'm not familiar with coupled runs like this, but  I believe the error would come from the coupled model initializing the relevant drydep variables from the shared module but not the elm specific ones used for OpenACC coupler bypass runs.  Removing the elm specific model should then make work as it should.

**Comment by tangq** [comment]
@peterdschwartz , I ran a new test (right) with your fix for 1 year. Comparing it to the same year of result from my previous simulation (left). The ozone and other tracer's (not shown here) dry deposition fluxes are very similar. Additionally, dead zero points are gone. I think this fixes the issue.

We need to merge your above branch to the master. Do you want to issue a PR? (Note: this PR won't change the E3SMv2 production results, but it's a non-BFB change for the simulations with the 'xactive_lnd' dry deposition method.)

I also noticed the peak ozone fluxes over inland seas, which should be unphysical. But it is a separate issue and seems only affect ozone. Do you have any insight? We can solve that in a separate PR. Thanks!

![Screen Shot 2021-08-20 at 9 18 03 AM](https://user-images.githubusercontent.com/8323089/130263641-b48bfa34-3b41-4255-ac6d-1820f48afe6b.png)
