### ISSUE TITLE
`namelist` error in coupler log

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/E3SM#4527]
`ERROR: (seq_flds_set) ERROR: namelist read returns an EOF or EOR condition` appears in the coupler log for many, if not all, Water Cycle coupled simulations using code including #4439.

Machine: Chrysalis
Cases: v2.LR.piControl, v2.LR.hist-GHG, v2.LR.hist-aer, v2.LR.hist-all-xGHG-xaer

**Comment by rljacob** [comment]
Is this a fatal error?

**Comment by forsyth2** [comment]
> Is this a fatal error?

Yes. The process completes with a non-zero exit code. Only the `e3sm` and `cpl` logs get written.

**Comment by forsyth2** [comment]
[E3SM_Issue_4527_run.v2.LR.piControl-test.txt](https://github.com/E3SM-Project/E3SM/files/7132351/E3SM_Issue_4527_run.v2.LR.piControl-test.txt)

Above is the run script I used. Notably:
```
readonly CHECKOUT="20210831"
readonly BRANCH="bb8fab659a8a384cbaeec9c34881b493110b1a08" # master after 4439 merged
```

**Comment by golaz** [comment]
@jonbob and @rljacob : this is a very strange issue. On the surface, it appears to be related to the addition of the new namelist parameter `rof2ocn_nutrients` in `seq_cplflds_inparm` from `drv_in` given where the model fails:

```
  0:  ERROR: (seq_flds_set) ERROR: namelist read returns an EOF or EOR condition
  0: Image              PC                Routine            Line        Source             
  0: libpnetcdf.so.3.0  000015555406C15A  tracebackqq_          Unknown  Unknown
  0: e3sm.exe           0000000004E4B520  shr_abort_mod_mp_         114  shr_abort_mod.F90
  0: e3sm.exe           0000000004E0296F  seq_flds_mod_mp_s         422  seq_flds_mod.F90
  0: e3sm.exe           000000000044D75C  cime_comp_mod_mp_        1086  cime_comp_mod.F90
  0: e3sm.exe           0000000000455B99  MAIN__                    112  cime_driver.F90
  0: e3sm.exe           0000000000425922  Unknown               Unknown  Unknown
  0: libc-2.28.so       0000155550CEB7B3  __libc_start_main     Unknown  Unknown
  0: e3sm.exe           000000000042582E  Unknown               Unknown  Unknown
```

However, I have looked at the code mods in `seq_flds_mod.F90` from https://github.com/E3SM-Project/E3SM/pull/4439 and I just don't see what could be wrong. The input `drv_in` file that @forsyth2 is using also looks fine as far as I can tell.

**Comment by jonbob** [comment]
@forsyth2 - is there a case and run directory I can look at that already shows this error?

**Comment by golaz** [comment]
@jonbob, here is one of Ryan's test that failed with the namelist error:

/lcrc/group/e3sm/ac.forsyth2/E3SMv2/v2.LR.piControl-test/tests_0101_post_4439/XS_1x10_ndays

**Comment by jonbob** [comment]
Thanks @golaz

**Comment by jonbob** [comment]
@forsyth2 - does this happen for you with master as well? I agree from the logs of your failed run that the problem is with rof2ocn_nutrients, but the thing is I'm having trouble replicating this. I've run tests on both anvil and chrysalis using master, a clean checkout of the hash your script points to, and even your codebase -- and so far it all works fine. I've duplicated your test as closely as I can but can't get mine to fail. I do have a question about your script -- I can't tell where the GIT_DESCRIBE file ends up so I can verify the hash. On further digging, I'm wondering if your test is trying to run with an older copy of e3sm.exe. The preview_run.log file shows:
````
      srun --mpi=pmi2 -l -n 896 -N 14 --kill-on-bad-exit   --cpu_bind=cores  -c 2 -m plane=64 /lcrc/group/e3sm/ac.forsyth2/E3SMv2/v2.LR.piControl-test/build/e3sm.exe   >> e3sm.log.$LID 2>&1
````
but listing that executable shows is was built on July 22?
````
-rwxrwx--x+ 1 ac.forsyth2 E3SM 175158088 Jul 22 17:46 /lcrc/group/e3sm/ac.forsyth2/E3SMv2/v2.LR.piControl-test/build/e3sm.exe
````
Does that make any sense to you?

**Comment by forsyth2** [comment]
>  does this happen for you with master as well?

Let me try running using E3SM as of today.

> listing that executable shows is was built on July 22?

I was using an old executable on some tests (i.e., setting `readonly OLD_EXECUTABLE`), but I didn't do that for this run. **Is that my problem then, that `/lcrc/group/e3sm/ac.forsyth2/E3SMv2/v2.LR.piControl-test/build/` never got overwritten?** I thought by checking out newer code it would rebuild the executable. Let me try running after deleting/moving this build directory....

**Comment by rljacob** [comment]
If you check out new code in mpas-framework, the build may not recognize it.  See https://github.com/E3SM-Project/E3SM/issues/4341

**Comment by jonbob** [comment]
I think that's it -- but I don't regularly use the run scripts so I'm not sure what they do. But it does make sense if it used a recent hash to set up namelists but then an old executable didn't recognize some of the newer additions. In some ways it's the only explanation that makes much sense?

**Comment by jonbob** [comment]
@rljacob - that new code was in driver_mct

**Comment by rljacob** [comment]
Oh that should rebuild.  I was just doing that myself (a case dir pointing to one srcroot, switching branches and rebuilding).

**Comment by jonbob** [comment]
I think the problem is in the run script, in this section:
````
# --- Toggle flags for what to do ----
do_fetch_code=false
do_create_newcase=true
do_case_setup=true
do_case_build=false
do_case_submit=true
````
It appears to setup up a new case without building it? That seems inherently dangerous to me.... though I can imagine it could sometimes be useful to reuse a single build for several related tests

**Comment by forsyth2** [comment]
> I can imagine it could sometimes be useful to reuse a single build for several related tests

Yes, the case existed from previous runs. I was rerunning the tests with the latest code.

**Comment by forsyth2** [comment]
I ran a test with a new case build and it completed successfully. Thank you for the information regarding the case build!

**Comment by jonbob** [comment]
@forsyth2 - do you want to close this issue then? Are you OK with the resolution?

**Comment by forsyth2** [comment]
@jonbob Yes, I think we can close this issue. Thanks!

**Comment by jonbob** [comment]
Great -- glad to help

**Comment by golaz** [comment]
@jonbob : sorry for causing you to waste your time. I should have caught the mistake earlier when things just did not make sense.

Yes, the `do_case_build` and `OLD_EXECUTABLE` are somewhat dangerous options. But they do come in handy because it takes a long time to rebuild even if nothing has changed in the source code. This is particularly useful when we launch a series of small test jobs.

**Comment by jonbob** [comment]
@golaz - no problem. I was afraid you had found a bad issue, and it's just hard to make sense when things don't add up. I'm just glad to make sure it wasn't a real bug and that we could figure it out. Hmmm, I can see the use for those dangerous options -- but also potential problems. It concerned me that I couldn't find a GIT_DESCRIBE file anywhere as part of the run, because that could have made it clear. Was I just not seeing it? Or if it's not there, would it be possible to make sure it gets generated for every test?
