### ISSUE TITLE
Missing data on blues server: inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#4764]
While trying on lawrencium machines at LBL, @jenniferholm found that we are missing some data on "blues" as her case could not download from:
`inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar`

I do see the dir at NERSC in CFS.

**Comment by ndkeen** [comment]
Unless someone objects, I just started a globus transfer of the directory:
`/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar` at NERSC

to 

`/lcrc/group/e3sm/public_html/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar` on blues which was not there.

**Comment by ndkeen** [comment]
@jenniferholm can you confirm that copying this data in place corrected the issue you were seeing?

**Comment by jenniferholm** [comment]
@ndkeen - sorry for my slow response.  I see that you did copy over the /Solar/ data at the link below.  But when on Lawrencium and using wget, it still has an error. Not sure why.  I attached my error message below when trying to download one of the input data files. 
Any thoughts?  Maybe my "wget" settings aren't set up correctly.  
On a side note, it does seem that only the directory path name needs to be updated from Solar/ to Solar3Hrly/ instead of copying over the same (duplicate) input data.  

https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar/

Loading input file list: 'Buildconf/mosart.input_data_list'
Loading input file list: 'Buildconf/cpl.input_data_list'
Using protocol wget with user  and passwd 
Using protocol svn with user  and passwd 
Client protocol None not enabled
Checking server https://web.lcrc.anl.gov/public/e3sm/inputdata/ with protocol wget
Using protocol wget with user  and passwd 
Loading input file list: 'Buildconf/datm.input_data_list'
Model datm missing file file1 = '/global/scratch/jaholm/ccsm_inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar/clmforc.GSWP3.c2011.0.5x0.5.Solr.1948-01.nc'
Trying to download file: 'atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar/clmforc.GSWP3.c2011.0.5x0.5.Solr.1948-01.nc' to path '/global/scratch/jaholm/ccsm_inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar/clmforc.GSWP3.c2011.0.5x0.5.Solr.1948-01.nc' using WGET protocol.
wget failed with output:  and errput --2022-02-08 11:48:51--  https://web.lcrc.anl.gov/public/e3sm/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar/clmforc.GSWP3.c2011.0.5x0.5.Solr.1948-01.nc
Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.70.30
Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.70.30|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-02-08 11:48:51 ERROR 404: Not Found.

**Comment by ndkeen** [comment]
Ah, OK it looks like that even the data I copied from Cori->blues is missing certain years:

I see 1901-2010, except for these missing years:

```
-rw-rw-r--+  1 qzhu     qzhu     259202520 Jul 28  2017 clmforc.GSWP3.c2011.0.5x0.5.Solr.1931-12.nc
-rw-rw-r--+  1 qzhu     qzhu     259202520 Jul 28  2017 clmforc.GSWP3.c2011.0.5x0.5.Solr.1932-01.nc
-rw-rw-r--+  1 qzhu     qzhu     234319224 Jul 28  2017 clmforc.GSWP3.c2011.0.5x0.5.Solr.1932-02.nc
-rw-rw-r--+  1 amschnei amschnei 259202520 Jul 28  2017 clmforc.GSWP3.c2011.0.5x0.5.Solr.1981-01.nc
-rw-rw-r--+  1 amschnei amschnei 234319224 Jul 28  2017 clmforc.GSWP3.c2011.0.5x0.5.Solr.1981-02.nc
-rw-rw-r--+  1 amschnei amschnei 259202520 Jul 28  2017 clmforc.GSWP3.c2011.0.5x0.5.Solr.1981-03.nc
```

ie, 1933-1980 ?

**Comment by jenniferholm** [comment]
Oh yea, I see those years are missing too. Weird.  
Eventually, I will also need the same atm forcing input data for Precip/ and TPHWL/ as well.  And the data files for TPHWL are a lot larger in size. Hence why I was thinking it would be better to just update the directory path (in Blues? Or in a config file?)

**Comment by bishtgautam** [comment]
@jenniferholm, @ndkeen, The `atm_forcing.datm7.GSWP3.0.5d.v1.c170516` is from CESM and wasn't created by E3SM. @rljacob can correct me, but I think we (E3SM) shouldn't be hosting that data on the e3sm public server. You can directly download the data on Lawrencium from https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/

**Comment by jenniferholm** [comment]
@bishtgautam - oh, good point about being from CESM. 
@ndkeen - exactly. The needed data, and same files are already in atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar3Hrly
atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Precip3Hrly
atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/TPHWL3Hrly

Can you help me update the lookup directory path?

**Comment by bishtgautam** [comment]
I'm not sure why the dir on e3sm's server has a suffix `3Hrly`.

**Comment by ndkeen** [comment]
Hmm, not sure how best to leave this. If we don't want this data on e3sm server, should we then delete:
```
atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar3Hrly
atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar
```
on both blues and cori?

Or at least, assuming these 2 dirs are holding the same files (with one being more complete), should we delete one of them?

@jenniferholm at least for now, I think you will need to find where this path is being set in your case and change it to `Solar3Hrly` -- somewhere it must be set to `Solar`

**Comment by mt5555** [comment]
I'll confirm that NCAR produced data should not be put on the E3SM dataserver.  NCAR needs to control when/how their data sets are made publicly available.  When a user setups a case, CIME will look for datasets on both servers and is supposed to download the missing ones to the local machine.

**Comment by rljacob** [comment]
NCAR serves the data but once its downloaded to the local inputdata dir, it should stay there.  So don't delete it from cori if its in DIN_LOC_ROOT.  Or blues.   Do delete it from /lcrc/group/e3sm/public_html/inputdata on blues if its a duplicate of NCAR data.

**Comment by ndkeen** [comment]
What about the fact that there looks like duplicate data in 2 dirs that have similar names?

**Comment by rljacob** [comment]
Yes /lcrc/group/e3sm/public_html/inputdata is the directory blues serves data from.  Its separate from the DIN_LOC_ROOT on blues/chrysalis.

No one has actually gone through and checked for all the duplicates between NCAR's server and ours.  I don't think its a priority.

If 2 dirs have the same data, someone needs to figure out which to keep.

**Comment by bishtgautam** [comment]
@qzhu-lbl @dmricciuto Do you know what is the difference between the files in the following dirs?

```
atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar3Hrly
atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar
```

**Comment by jenniferholm** [comment]
@bishtgautam - I don't think there is any difference between the files in the two directories (they are duplicates). 

atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar3Hrly
atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar

To resolve this issue I think I just need to update the directory path to have the "3Hrly" suffice. It's not really an issue of "missing data".  I'll update my directory paths in Lawrencium, and I think all will be good.  I'll let you all know when I do this.

**Comment by jenniferholm** [comment]
@bishtgautam , or others -- could someone give me a heads up where I can manually (and permanently) change the filePath in the three datm streams files?  Every time I manually change the path from /Solar to /Solar3Hrly it gets overwritten at with the case.build or case.submit stage. 

datm.streams.txt.CLMGSWP3v1.Solar
datm.streams.txt.CLMGSWP3v1.Precip
datm.streams.txt.CLMGSWP3v1.TPQW

Thanks for your help.

**Comment by bishtgautam** [comment]
@jenniferholm Can you provide the command that are you are using to create the case?

**Comment by jenniferholm** [comment]
[create_prr_fatescnp_elm_lr3.txt](https://github.com/E3SM-Project/E3SM/files/8043158/create_prr_fatescnp_elm_lr3.txt)

**Comment by jenniferholm** [comment]
No worries on this issue anymore. I figured out where to update the stream directory paths. 
Here: 
./cime/src/components/data_comps_mct/datm/cime_config/namelist_definition_datm.xml
./components/data_comps/datm/cime_config/namelist_definition_datm.xml

**Comment by ndkeen** [comment]
Should I then delete the files in `atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar` as they are duplicate?

**Comment by jenniferholm** [comment]
Yes, sounds good to delete the duplicate atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar files, and go ahead and close this issue.

**Comment by ndkeen** [comment]
`/global/cfs/cdirs/e3sm/inputdata/atm/datm7/atm_forcing.datm7.GSWP3.0.5d.v1.c170516/Solar` has now been removed
