### ISSUE TITLE
Implicit vertical mixing routines cause out of bounds error for single layer

### ISSUE THREAD

**Issue by sbrus89** [E3SM-Project/E3SM#4849]
This was discovered in recently developed single layer configurations used for barotropic tidal modeling under the ICoM project. The error appears to occur after the in-lining of the tridiagonal solves in the vertical mixing routines in #4680. For a single layer, this should solve a 1x1 matrix by simply dividing  the rhs by the diagonal value. In the code below, `layerThicknessEdge(Nsurf+1,iEdge)` causes the initial out of bounds error.

https://github.com/E3SM-Project/E3SM/blob/b404a464a55dbdad1f13bdc63ff7b6077527426e/components/mpas-ocean/src/shared/mpas_ocn_vmix.F#L857-L862

**Comment by philipwjones** [comment]
@sbrus89 - Sorry for the delay in looking at this. I've been refactoring these routines to reduce the number of implicit routines so I'm happy to include a fix.  But looking at this more closely, I'm not sure what vertical mixing means in a single layer context or what the discretization should be if it is being used? If you just need the drag term, then the explicit drag might be more appropriate? I guess I need more info because I don't see the existing routine as being valid at all in a single layer.
