### ISSUE TITLE
Missing input data on building F2010 with ne30pg2_ne30pg2 grid on Crusher and Summit

### ISSUE THREAD

**Issue by grnydawn** [E3SM-Project/E3SM#5054]
I failed to build F2010 compset case with ne30pg2_ne30pg2 grid on Crusher and Summit due to following missing input data issue.

The first line in the log below shows that mpas-cice gx1v6 input data is missing. The direct reason is that the filename of netcdf data is not well formed: double dots (..nc) could not be a valid file name.

From looking more detail, it turns out that the name generation python script in mpas cice does not generate proper netcdf file name, or gx1v6 is not supported grid for mpas-cice. I created a similar issue here (https://github.com/E3SM-Project/E3SM/issues/4908)

However, because ne30pg2_ne30pg2 grid is quite commonly mentioned in e3sm test cases, I wonder if this issue should be resolved properly to support several test cases on Crusher and Summit.

Following is a screen capture of e3sm building.

```
Model mpassi missing file mesh = '/gpfs/alpine/cli115/world-shared/e3sm/inputdata/ice/mpas-cice/gx1v6/..nc'
Trying to download file: 'ice/mpas-cice/gx1v6/..nc' to path '/gpfs/alpine/cli115/world-shared/e3sm/inputdata/ice/mpas-cice/gx1v6/..nc' using WGET protocol.
wget failed with output:  and errput --2022-06-29 13:20:56--  https://web.lcrc.anl.gov/public/e3sm/inputdata/ice/mpas-cice/gx1v6/..nc
Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.70.30
Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.70.30|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-29 13:20:56 ERROR 404: Not Found.

Model mpassi missing file graph64 = '/gpfs/alpine/cli115/world-shared/e3sm/inputdata/ice/mpas-cice/gx1v6/.part.64'
Trying to download file: 'ice/mpas-cice/gx1v6/.part.64' to path '/gpfs/alpine/cli115/world-shared/e3sm/inputdata/ice/mpas-cice/gx1v6/.part.64' using WGET protocol.
wget failed with output:  and errput --2022-06-29 13:20:56--  https://web.lcrc.anl.gov/public/e3sm/inputdata/ice/mpas-cice/gx1v6/.part.64
Resolving web.lcrc.anl.gov (web.lcrc.anl.gov)... 140.221.70.30
Connecting to web.lcrc.anl.gov (web.lcrc.anl.gov)|140.221.70.30|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-29 13:20:56 ERROR 404: Not Found.
```

My case creation command is similar to below.
```
RES=ne30pg2_ne30pg2
COMPSET="F2010"

${E3SM}/cime/scripts/create_newcase --case "${CASEDIR}" --res ${RES} --compset ${COMPSET}  --machine summit --project ${ACCOUNT} --output-root "${OUTROOT}"
```

**Comment by jonbob** [comment]
@grnydawn - I don't think the ne30pg2_ne30pg2 is used in our testing much anymore, since it does not show up in the E3SM tests.py. The default F compsets now use the mpas-seaice component for ice, and it requires the ice grid to be an mpas mesh. You could try F2010-CICE as the compset, which will use the cice model instead -- and should run on the gx1v6 mesh. Or you can change the resolution to ne30pg2_oECv3, which should be fine with the F2010 compset

**Comment by sarats** [comment]
FYI @mt5555 as you expected ne30pg2_ne30pg2 to work.

**Comment by sarats** [comment]
Related question for @mt5555 : is F2010 with ne30pg2_oECv3 **the** atm compset we should get working on machines like Crusher besides MMF and SCREAM. Or should it be F2010-CICE?

**Comment by grnydawn** [comment]
@jonbob, thanks for the explanation. That helps me understand better on compset/grid pair. I will try F2010/ne30pg2_oECv3. Thanks.

**Comment by mt5555** [comment]
@sarats : my mistake recommending ne30pg2_ne30pg2.   Yes, ne30pg2_oECv3  F2010 is the correct compset since it very close to how a B  case is run and it's the natural step towards fully coupled.      The single-grid compset is simpler and  useful in some cases (runs on fewer nodes, less mapping files, but as John pointed out, only the old CICE model can run ice thermodynamics on an atmosphere grid).

**Comment by sarats** [comment]
Thanks everyone for clarifying.
