### ISSUE TITLE
Multi-instance runs stall at last timestep

### ISSUE THREAD

**Issue by mkstratos** [E3SM-Project/E3SM#5122]
For F2010 compset (among others possibly) multi-instance runs do not finish before writing the final output files (e.g. in the MVK test https://my.cdash.org/test/60057626), on Chrysalis at the very least. This seems to be an issue with MPAS-SI, as the F2010-CICE does complete under the same number of instances. My thought is that multiple processes are attempting to write to the same MPAS-SI restart file.

**Comment by mt5555** [comment]
it will be great to get this fixed!  it's been failing for a while.

Could we disable restart altogether?  Probably not needed by this test or any of the other nbfb tests.   Better of course would be to fix MPAS-SI to work correctly with multiple instances, although their use is not common in E3SM. @jonbob might know if this is a simple tweak.  

It would be a shame to have to revert this test back to F2010-CICE also, since E3SM would like to eventually remove the CICE code.

**Comment by rljacob** [comment]
Is this fixed by #5125 or #5123 ?

**Comment by mkstratos** [comment]
This is fixed by #5123
