### ISSUE TITLE
Imprint of atmospheric grid visible on some surface sea ice fields

### ISSUE THREAD

**Issue by njeffery** [E3SM-Project/E3SM#5242]
A checkboard pattern is visible in monthly climatologies of melt-pond fraction for ne30 atm grids and EC30to60E2r2.

**Comment by rljacob** [comment]
Can you include a figure showing it?

**Comment by njeffery** [comment]
![pondAreaCellNH_v2 LR piControl_09_years0015-0116](https://user-images.githubusercontent.com/8211178/196525464-5d03a3b3-064c-41af-8e6c-fbe8d55d6ae6.png)

**Comment by whannah1** [comment]
@njeffery are you able to plot the atmospheric fields on the native grid?
If not then can you point me to where the data is?
I'd like to check a few fields.
This might be the same issue that I documented here:
https://acme-climate.atlassian.net/wiki/spaces/NGDAP/pages/2953512527/Checkerboard+noise+problem+related+to+the+dCAPE+trigger

**Comment by rljacob** [comment]
and the imprint is only in that field?  no others?

**Comment by njeffery** [comment]
I'm looking at some of the other fields now.  I suspect it'll show up in albedo, shortwave surfaces fluxes, that sort of thing.  

I looked at an RRM-EC30to60E2r2 run that @jonbob had done and the checkerboard disappeared in the Arctic (still present in the Southern Ocean). 

Chris's run is archived on NERSC. I have a comparable run on anvil that shows the same pattern. Here:
/lcrc/group/e3sm/ac.jeffery/E3SMv2/v2.snow.snowRedisOnly/run

**Comment by njeffery** [comment]
We made a change in v2 in how ponds form in response to snow melt.  There is a namelist flag that is intended to turn off that feature.  It's not coded properly at the moment but I'll change that soon and submit a PR.  With the snowmelt-to-pond flag false, the checkerboard disappears.  Here's a figure from a comparable run:


![pondAreaCellNH_small_v2 snow snowModsNoLiqPonds_06_years0010-0072](https://user-images.githubusercontent.com/8211178/196531619-e1cc411a-6fcf-43ee-8496-98fc2e6dec4c.png)

**Comment by rljacob** [comment]
Interesting.  Would still like to know if shows up in other fields (and if the flag matters for those).

**Comment by whannah1** [comment]
FYI I looked at a few fields from the run on LCRC that @njeffery pointed to. I mainly just plotted 1 or 10 year averages, but I'm not seeing any detectable checkerboard over the poles.
Here's an example of PRECT, but I just a similarly smooth looking field for liquid water path, which is usually the best field to detect the checkerboard problem that I've looked into previously.

![image](https://user-images.githubusercontent.com/9679059/196557855-db5efa23-6438-4e71-b81c-d5bf6ad4c3ad.png)

**Comment by njeffery** [comment]
Here are some other fields in MPAS-SI that see imprinting:

![absorbedShortwaveFluxInitialAreaNH_AI_ANN_v2 LR piControl_years0015-0116](https://user-images.githubusercontent.com/8211178/217074593-fcc4ba27-d068-4c5d-8360-0d00f25aa216.png)
![absorbedShortwaveFluxInitialAreaSH_AI_ANN_v2 LR piControl_years0015-0116](https://user-images.githubusercontent.com/8211178/217074689-3f7fe039-304f-474f-b064-29fc77f8ffd6.png)
![pondAreaCellNH_AI_v2 LR piControl_06_years0015-0116](https://user-images.githubusercontent.com/8211178/217074823-e27cbb53-d098-4f55-bc9b-6cb86b008474.png)
![snowMeltNH_AI_ANN_v2 LR piControl_years0015-0116](https://user-images.githubusercontent.com/8211178/217074885-efa9ae31-c88b-4c80-b038-c913c5620b55.png)

**Comment by proteanplanet** [comment]
Here is another example of atmospheric mesh imprinting on the sea ice and ocean models, this time for the coupler field o2x_So_dhdx passing from ocean to ice:  

In the coupler field of sea surface height being passed from the ocean model to the sea ice model, the atmospheric mesh is imprinted on the gradient height field, meaning it has (probably) derived from the atmospheric turbulent flux fields.  This is for the WC14 ocean-ice mesh coupled with the standard-resolution atmosphere.  One would expect some imprinting with this resolution discrepancy, but the fact it occurs mainly in the Canadian Archipelago and Greenland coastal regions suggests land/atmosphere coupling and/or coastal weighting are somehow involved.

![InteRFACE1alphaC cpl hi 0036-01-09-28800 o2x_So_dhdx nh](https://user-images.githubusercontent.com/14379090/217098967-ef40ef4b-06f9-4caa-8364-86c38ae8938a.png)

![InteRFACE1alphaC cpl hi 0036-01-09-28800 o2x_So_dhdy nh](https://user-images.githubusercontent.com/14379090/217098998-c7eae970-d2b8-4f0e-9df8-8aa0129c1697.png)

The area around Greenland is zoomed for convenience here for dh/dy: 

![InteRFACE1alphaC cpl hi 0036-01-09-28800 o2x_So_dhdy nh zoom](https://user-images.githubusercontent.com/14379090/217099223-aaad6751-df7f-4123-ab7c-4d327bde17e1.png)

**Comment by rljacob** [comment]
Are the areas the imprinting is seen also under sea ice?   What controls sea surface height under sea ice?

**Comment by proteanplanet** [comment]
For completeness, I'm going to post a compressed file here of every relevant coupled flux and state field to the ice and ocean so that you can step through them.  But here is the summary so far:  Aside from the (dh/dx,dh/dy) o2x gradient field, which results, in winter, from ice-ocean stress, in turn driven mainly by the wind stress (hence affected by the surface radiation balance), the main imprint appears to come from precipitation and radiation, for which I'm sharing x2i snow for the northern hemisphere, and x2i long wave up (which is usually balanced by longwave down). 

![InteRFACE1alphaC cpl hi 0036-01-09-27000 x2i_Faxa_snow nh](https://user-images.githubusercontent.com/14379090/217109161-71a0923a-3121-4dcd-a3d8-8e2cbd561260.png)

![InteRFACE1alphaC cpl hi 0036-01-09-27000 x2i_Faxa_lwdn sh](https://user-images.githubusercontent.com/14379090/217117321-c4fc6890-951c-4b18-b12f-d503e75460bc.png)

It'll take me 24 hours to complete the generation of fields, but I've already looked through most of them.

**Comment by proteanplanet** [comment]
Please see attached important atmospheric coupled fields used to calculate energy fluxes when there is little to no sunlight affecting the northern hemisphere pack.  These results are very solid, because they are an average of 500 years form the PI Controls from v2 standard resolution and NARRM:

[July_19_Ice_Group_Brief_E3SM.pdf](https://github.com/E3SM-Project/E3SM/files/12098226/July_19_Ice_Group_Brief_E3SM.pdf)

The problem appears to be temperature related, since the V2 aliasing is apparent in sensible heat, but only mildly in latent heat, and not in the wind field.  It is evident in both the NARRM and SR simulations. I'm attaching the PNG here of the latent heat plot shown above, so that you can zoom into that particular figure to see the alias even at high resolution.

![NARRM_LR_0001_0500_PI_sensible_NH](https://github.com/E3SM-Project/E3SM/assets/14379090/d032b7dc-0634-4fa4-b191-ae701300fb7b)

There is no aliasing as such in the surface longwave down, although the atmospheric grid is definitely noticable, which is not unexpected:
 
![NARRM_LR_0001_0500_PI_longwavedown_NH](https://github.com/E3SM-Project/E3SM/assets/14379090/0a75803e-ecc1-49e5-b4da-518aac2bbb84)

These fields are as seen from inside the sea ice model.

**Comment by proteanplanet** [comment]
Addendum:  All of the above figures are plotted on the native mesh (no interpolation), and therefore are different from results that would appear in MPAS-Analysis.

**Comment by eclare108213** [comment]
@proteanplanet @njeffery 
Has this issue improved in the new version?

**Comment by proteanplanet** [comment]
@eclare108213: Yes.  We are now using non-linear remapping between the ocean/ice and atmosphere, and as a result the imprint of the atmospheric mesh is reduced, and has allowed us to discover other issues associated with the interaction of Redi with ice shelves that previously were aliased-out by linear remapping.  Here is an example of sea ice production around the Antarctic, with the non-linear and linear maps, respectively, for sea ice production. There are other differences between these simulations, but the figures highlight the impact of non-linear remapping:

![seaice_productionSH_antarctic_extended_20231122 v3b02-Icos30 piControl chrysalis_JJA_years0101-0150](https://github.com/E3SM-Project/E3SM/assets/14379090/225d333a-bfb3-4273-b6ff-d180ff0cb8e7)

![seaice_productionSH_antarctic_extended_20230808 v3alpha02 piControl chrysalis_JJA_years0101-0150](https://github.com/E3SM-Project/E3SM/assets/14379090/effcdf3e-aba9-4ae7-a204-f9c908535855)

**Comment by proteanplanet** [comment]
I suggest this issue could be closed and marked resolved, with thanks to @ambrad for the non-linear remappping.

**Comment by njeffery** [comment]
Much improved with new non-linear remapping between components.
