### ISSUE TITLE
Array bound mismatch for dimension 1 of array 'elm_idata' with GNU

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/E3SM#5249]
With `SMS_D.f09_g16.I1850ELMCN.cori-knl_gnu.elm-bgcinterface` and Oct 25th master, I see:

```
 16: At line 288 of file /global/cfs/cdirs/e3sm/ndk/repos/me06-oct25/components/elm/src/main/elm_interface_funcsMod.F90
 16: Fortran runtime error: Array bound mismatch for dimension 1 of array 'elm_idata' (8/9)
```

This DEBUG test passes (for example):
`SMS_D.f09_f09.IELM.cori-knl_gnu.elm-solar_rad`

**Comment by bishtgautam** [comment]
@peterdschwartz, I believe this error is related to ELM PFLOTRAN interface.

**Comment by peterdschwartz** [comment]
@bishtgautam 
Might be a same cause as Issue #4492 , which i left as unresolved since I wasn't certain what the intended fix should be as I am not really familiar with the elm_interface runs.  Do you think it's better to change the allocation of elm_interface_bgc_datatype to `0:ndecomp_pools` or to change the assignments to 

`elm_idata%bgc%decomp_pool_name(1:ndecomp_pools)    = decomp_pool_name(1:ndecomp_pools)  `

From that issue: 
========================================================================
The error is that some decomp_cascade_con fields are allocated starting from 0 but the corresponding fields for the elm interface data types are allocated starting at 1.
```
elm_interface_bgc_datatype:
allocate(this%decomp_pool_name (1:ndecomp_pools)) 
allocate(this%floating_cn_ratio (1:ndecomp_pools))
allocate(this%floating_cp_ratio (1:ndecomp_pools))
```
versus
```
allocate(decomp_cascade_con%decomp_pool_name_history(0:ndecomp_pools)) allocate(decomp_cascade_con%floating_cn_ratio_decomp_pools(0:ndecomp_pools)) allocate(decomp_cascade_con%floating_cp_ratio_decomp_pools(0:ndecomp_pools))
```

It's not clear if the fix should be to fix the allocation or the assignment since some interface type are allocated from 0 (eg, this%initial_cn_ratio) and some of the assignments do slice from 1:ndecomp_pools (e.g. decomp_k_pools).

**Comment by bishtgautam** [comment]
The assignment should be changed because in other F90 files the code is implemented assuming indices are `1:elm_pf_idata%ndecomp_pools` e.g., [elm_interface_pflotranMod.F90#L822](https://github.com/E3SM-Project/E3SM/blob/master/components/elm/src/main/elm_interface_pflotranMod.F90#L822)

**Comment by peterdschwartz** [comment]
That should make this a simple one line change then.  I will test it out.
It was confusing as some parts of the bgc data type go from 0 like [elm_interface_bgcType.F90#L249](https://github.com/E3SM-Project/E3SM/blob/master/components/elm/src/main/elm_interface_bgcType.F90#L249)

**Comment by ndkeen** [comment]
Oh, I see -- you already noted above that this is maybe same as a pretty old issue I created https://github.com/E3SM-Project/E3SM/issues/4492
