### ISSUE TITLE
Kokkos inventory and possibility of convergence

### ISSUE THREAD

**Issue by sarats** [E3SM-Project/E3SM#5417]
There seem to be a couple of versions of Kokkos floating around in the E3SM and SCREAM repositories.

Starting this discussion to understand our Kokkos dependencies and see if we can converge on requirements to avoid confusion/redundancy. 

One of them is through SCREAM/EKAT 
https://github.com/E3SM-Project/EKAT/tree/master/extern
> [kokkos @ e8ad274](https://github.com/E3SM-Project/kokkos/tree/e8ad274447f11582cef98f0aa409d8ee06d2c7fa)
[Update extern/kokkos to e3sm-kokkos-3.7.00-tag](https://github.com/E3SM-Project/EKAT/commit/85062686615d99547ddd494ef8b97f72b5c63a54)
> 3 months ago

Another is under https://github.com/E3SM-Project/E3SM/tree/master/externals
> [kokkos @ 290a073](https://github.com/E3SM-Project/kokkos/tree/290a073f38c024ba37113716d7ed4ac921f3db85)
[Update kokkos module with Fujitsu compiler mods](https://github.com/E3SM-Project/E3SM/commit/ea12e8d167bb342a9f2fc328a9ced4852042b5de)[kokkos @ 290a073](https://github.com/E3SM-Project/kokkos/tree/290a073f38c024ba37113716d7ed4ac921f3db85)
[Update kokkos module with Fujitsu compiler mods](https://github.com/E3SM-Project/E3SM/commit/ea12e8d167bb342a9f2fc328a9ced4852042b5de)
> 9 months ago

During a recent meeting, there was a comment that the version under E3SM/externals is used for SL transport CPU builds? 

cc @mt5555 @ambrad

**Comment by ambrad** [comment]
SL transport is not the issue. SL transport can and does use either, of necessity; it accommodates a large number of configurations because of development and deployment history: standalone Homme F90, standalone Homme C++, E3SM CIME F90, E3SM CIME C++, SCREAM CIME C++.

The different Kokkos sources are because of EAMxx and EAM development history. EAMxx uses externals/ekat/kokkos, which currently exists only the SCREAM repo; EAM uses externals/kokkos.

The different Kokkos versions result from SCREAM or E3SM updating their Kokkos submodules independently.

I think there is general agreement that eventually E3SM should use ekat/kokkos. That might happen soon.

Attn: @jgfouca @bartgol.

**Comment by bartgol** [comment]
There is also another E3SM-related customer of Kokkos, and that's Albany, when mpas-albany-landice is active. Albany uses kokkos through the trilinos installation. A recently merged PR in e3sm, however, allows a compset to use kokkos from a user provided installation (via env var), much like it's possible for pio.

That aside, Andrew is right, saying that eventually ekat/kokkos should be used. On my "one day I'll find the time" todo list there is to make homme use ekat, so that no other customer of externals/kokkos should exist (unless I missed other kokkos customers).

Another important task is ensuring that all customers of kokkos are aware that kokkos might have been initialized by another component (maybe the e3sm driver?), so that they do not call the initialized and/or the finalize methods which, much like MPI_Init/MPI_Finalize, must be called exactly once, before/after any use of kokkos stuff.

If you guys are trying to plan a solution for a single submodule in the short term, we should prob have a conversation, and discuss timeline/approaches.

**Comment by sarats** [comment]
Yes, I'm trying to find all the Kokkos customers and gather perspectives on how to get to a common path in the future. There is no urgency per se.

The init/finalization would probably require some coordination at the driver/coupler level and other components using Kokkos especially in the numerous configurations that need to be supported. FYI @rljacob.

**Comment by bartgol** [comment]
Notice that #5416 will bring EKAT inside E3SM, so we will be in a position where `ekat/kokkos` _does_ exist in e3sm. We might consider planning a switch after that.

**Comment by sarats** [comment]
Just noting that the SCREAM PR https://github.com/E3SM-Project/E3SM/pull/5416 is now merged. 
We should consider any next steps as warranted.

**Comment by bartgol** [comment]
I guess the next step could be to make Homme use the version of kokkos in ekat. There are other things from ekat that Homme could use anyways (like packs, or the tridiag solver), to avoid code duplication

**Comment by rljacob** [comment]
@bartgol @oksanaguba how do we make the above happen?  It is time.

**Comment by bartgol** [comment]
Can we confirm that Hommex, Compose, and EAMxx are _the only_ users of kokkos in E3SM?

**Comment by mt5555** [comment]
EAM-MMF configurations also use Kokkos, and in a complex way:

On GPU systems:  MMF is running on the GPU, using C++/Kokkos versions of P3 and SHOC

But the EAM dycore is left on the CPU, where SL transport needs Kokkos with CPU support.

**Comment by bartgol** [comment]
Well, the Kokkos version of P3/SHOC uses ekat, I think, right? And SL transport is inside Homme, so it uses the same hooks that Homme uses to grab a kokkos distro. So in my mind, the two users are still just Homme and EAMxx.

**Comment by ambrad** [comment]
I agree with Luca: SL transport uses any Kokkos it's given, so externals/ekat/extern/kokkos is fine for every part of the dycore and EAMxx physics.

**Comment by jgfouca** [comment]
When homme is change to use EKAT, I will change the related CIME build code to switch everything to EKAT.

**Comment by rljacob** [comment]
Who can change homme to use EKAT?  @oksanaguba ?

**Comment by jgfouca** [comment]
@rljacob , I don't think it would be hard to do. I could probably do it but @oksanaguba or @bartgol would be the obvious choices.

**Comment by oksanaguba** [comment]
If @jgfouca could do it, it would be great, thank you.

**Comment by jgfouca** [comment]
@oksanaguba , ok, I will take a look at it soon.

**Comment by bartgol** [comment]
FYI, I'm working on making Homme use kokkos from ekat (dropping the need for external/kokkos). In a subsequent PR, I will work on making Hommexx use ekat for a few things (e.g., pack type, tridiag solver,...). Notice that in that following PR we will have to drop the possibility to use hommexx with eam (only eamxx will be allowed for kokkos dycore).
