### ISSUE TITLE
V3 chemistry changed climate for base cases.

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#5701]
PR https://github.com/E3SM-Project/E3SM/pull/4707 did not activate the backwards compatibility for v2 chemistry.   Surface ozone decay was off.   This caused tropospheric ozone  to grow and warmed the troposphere even for regular cases without any v3 features.    Was not seen in testing because we don't test for climate and the PR was non-BFB for other reasons so was blessed.  HOWEVER:  The MVK non-bfb test did spot a climate difference but we did not notice because it was failing for other reasons.  See https://github.com/E3SM-Project/E3SM/issues/5695

See run by @proteanplanet https://acme-climate.atlassian.net/wiki/spaces/PSC/pages/3771400193  Sea ice went away.

**Comment by tangq** [comment]
This backwards compatibility issue of ozone surface e-folding decay has been fixed in https://github.com/E3SM-Project/E3SM/pull/5687. The [50-year test](https://acme-climate.atlassian.net/wiki/spaces/ATMOS/pages/3785392374/Ozone+Surface+Loss+Fix+for+V2+configuration+Chrysalis+test2) confirms that the [tropospheric ozone](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zke/B12.baseline.master.E3SM-Project.chrysalis.t2/e3sm_diags/atm_monthly_180x360_aave/) is reasonable over 50 years and so is the [sea ice](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zke/B12.baseline.master.E3SM-Project.chrysalis.t2/mpas_analysis/ts_0001-0050_climo_0001-0010/sea_ice/index.html#timeseries&gid=11&pid=1). The 50-year [global time series](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.zke/B12.baseline.master.E3SM-Project.chrysalis.t2/global_time_series/global_time_series_0001-0050_results/O3.fixed.png) looks stable too.

**Comment by rljacob** [comment]
Yes that's right.

**Comment by rljacob** [comment]
Fixed by #5687
