### ISSUE TITLE
Sync MAM5 code with new edits resulting from VBS SOA decoupling

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/E3SM#5733]
> @keziming This will likely affect MAM5 as well. If you can change your MAM5 code accordingly at this stage in your PR from cnst_OH to prsd_OH, it would be great. I know there are some places you need to read in cnst_OH and do calculations for strat sulfate formation. Given the tight timeline, it is also fine that we do it later when turning on all features.

_Originally posted by @mingxuanwupnnl in https://github.com/E3SM-Project/E3SM/pull/5719#discussion_r1207145230_

--

This issue is to keep track of a potential conflict between MAM5 and the decoupled VBS SOA. Please refer to the original PR and the comments therein for reference. This is a temporary placeholder.

xref:
- MAM5 PR: https://github.com/E3SM-Project/E3SM/pull/5703
- VBS SOA decoupling PR: https://github.com/E3SM-Project/E3SM/pull/5719

**Comment by keziming** [comment]
@mahf708 Thank you for bring this up, and it is important to have clarification about this issue. In short answer, there is no conflict between MAM5 and new VBS-SOA chemistry. 

As chemUCI applies to the troposphere and sets chemistry solvers, implicit and explicit, off above tropopause. For stratospheric aerosol purpose, MAM5 uses explicit solver to solve sulfur chemistry (SO2, H2SO4, DMS) and imports prescribed oxidants instead of chemUCI oxidants in the stratosphere. The reason to use prescribed oxidants in the stratosphere is due to chemUCI doesn't reach to stratosphere. These changes are in mo_exp_sol.F90 and mo_gas_phase_chemdr.F90. 

On the other hand, VBS-SOA uses prescribed oxidants to decouple its chemistry with chemUCI. All these reactions are in the troposphere and in implicit solver. The prescribed oxidants are imported from the same file MAM5 used. Therefore, I don't see a directly conflict but I will set a run to test it.

**Comment by mingxuanwupnnl** [comment]
@keziming Both MAM5 and VBS SOA will need prescribed oxidant, NO3 and OH, from the same file. According to @tangq suggestion, I changed oxidants vars from cnst_xx to prsd_xx in chem mech in file. I think It is better we use the same namelist setting:
from
`tracer_cnst_specifier          = 'CH4','cnst_O3:O3','cnst_NO3:NO3','cnst_OH:OH'` 
to
`tracer_cnst_specifier          = 'CH4','prsd_O3:O3','prsd_NO3:NO3','prsd_OH:OH'`
Otherwise, we need two sets of oxidants, one (cnst_xx) for MAM5, and one for VBS SOA (prsd_xx). I think it is necessary.
