### ISSUE TITLE
Consider changing levels to heights or pressures in chem diags

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/E3SM#5790]
xref: https://github.com/E3SM-Project/E3SM/pull/5781#discussion_r1248942001

PR https://github.com/E3SM-Project/E3SM/pull/4707 introduces new chemistry diagnostics. Some of them rely on namelist parameters that provide the level index of starting and ending levels corresponding to certain fields. For example:

https://github.com/E3SM-Project/E3SM/blob/9e17b77a4e9ae91874b2fc56f248b5046bdce473/components/eam/src/chemistry/mozart/mo_chm_diags.F90#L1643-L1665

where parameters like `gaschmbudget_2D_L2_s` and `gaschmbudget_2D_L2_e` correspond to levels (given by their respective index). 

In the future, it may help to rely on physics-meaningful qualities like height or pressure so that these new diagnostics could be readily used with any new configuration without needing to manually edit anything.

**Comment by tangq** [comment]
Note: such diagnostics require using model levels, instead of heights or pressure.

The key question is to find a better way to satisfy these:
- Diagnostics based on model levels.
- When changing model levels (e.g., L72 to L75), the diagnostics still work.

**Comment by tangq** [comment]
Thanks for the suggestion, @mahf708 . I am pinning @hsiangheleellnl , who is the developer of this diagnostic. She is on vacation and will look at this when back.

**Comment by rljacob** [comment]
Since you really want those to be between specific pressure values which happen to correspond to specific level indicies in the L72 config, then yes the more robust way is what @mahf708 suggested and you would need a check for if those pressure values exist at all and take some action if they don't (hard fail, warning, etc.).

An EAM feature is that you can set the number of levels at compile time and all code should tolerate that number changing.

**Comment by tangq** [comment]
Thank you both for the suggestions, which will make the code better. @hsiangheleellnl will know more details about this. Since this one is not a high priority task, I will let @hsiangheleellnl to decide the best way to pursuit when she's back from vacation. We may close this one for now and reopen later.
