### ISSUE TITLE
add a pam test to gh/ci suite

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/E3SM#6766]
Objective: avoid breaking PAM. 
Background: PAM uses some EAMxx internals in specific ways that we often change.
Solution: Add one PAM/MMF2 test to gh/ci such that when specific files are touched, it is triggered to safeguard against breaking the test

**Comment by rljacob** [comment]
What case were you trying to run?

**Comment by whannah1** [comment]
@mahf708 catching up on this - the MMF2 compsets should only be using prescribed aerosol. The prognostic aerosol capability was never completed. I suspect there's something about that test modifier that's adding those aerosol files to the namelist, but I don't understand that modifier, so I'm confused how to check this.

Perhaps these are the prescribed aerosol files... but that wouldn't really make sense because the MMF1 tests should be using the same files.

**Comment by whannah1** [comment]
yea - sounds like the compset parsing there is broken and the chemistry options options are being added to the CAM_CONFIG_OPTS.

**Comment by rljacob** [comment]
@jgfouca and @bartgol this is the thread about the difficulty in adding an MMF test to the gh/ci suite
